// apps/web-tma/src/components/home/EGameCard.tsx
import type { SlotGame } from '@/api/slots'
import GameImageCard from '@/components/game/GameImageCard'
import { useLocaleStore } from '@/stores/locale'
import { localizedGameName } from '@/utils/game'

interface Props { game: SlotGame; onTap: () => void; className?: string }

export default function EGameCard({ game, onTap, className }: Props) {
  const locale = useLocaleStore((s) => s.locale)
  return (
    <button
      type="button"
      className={className ?? 'flex-shrink-0 w-32 h-44 rounded-xl overflow-hidden active:scale-95 transition-transform'}
      onClick={onTap}
    >
      <GameImageCard
        variant="mirror"
        imageUrl={game.imageHqUrl ?? game.imageUrl}
        fallbackBg={['#1e1b4b', '#312e81']}
        name={localizedGameName(game, locale)}
        provider={game.provider}
      />
    </button>
  )
}

// apps/web-tma/src/components/home/EGameCard.vue
<script setup lang="ts">
import type { SlotGame } from '@/api/slots'
import GameImageCard from '@/components/game/GameImageCard.vue'
import { useLocaleStore } from '@/stores/locale'
import { localizedGameName } from '@/utils/game'

defineProps<{
  game: SlotGame
  variant?: 'mirror'
}>()
const emit = defineEmits<{ tap: [] }>()
const localeStore = useLocaleStore()
</script>

<template>
  <button
    type="button"
    class="flex-shrink-0 w-32 h-44 rounded-xl overflow-hidden active:scale-95 transition-transform"
    @click="emit('tap')"
  >
    <GameImageCard
      variant="mirror"
      :image-url="game.imageHqUrl ?? game.imageUrl"
      :fallback-bg="['#1e1b4b', '#312e81']"
      :name="localizedGameName(game, localeStore.locale)"
      :provider="game.provider"
    />
  </button>
</template>
