// apps/web-tma/src/App.tsx
import { useEffect, useRef } from 'react'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import AppShell from '@/views/AppShell'
import SplashPage from '@/views/SplashPage'
import GoogleAuthCallback from '@/views/GoogleAuthCallback'
import LoginSheet from '@/components/auth/LoginSheet'
import RedPacketSheet from '@/components/promotion/RedPacketSheet'
import { useAuthStore } from '@/stores/auth'
import { usePromotionStore } from '@/stores/promotion'

function MainApp() {
  const { phase, bootError, loginSheetOpen, closeLoginSheet } = useAuthStore()
  const { redPacketSheet, closeRedPacket } = usePromotionStore()

  const bootstrapped = useRef(false)
  useEffect(() => {
    if (bootstrapped.current) return
    bootstrapped.current = true
    void useAuthStore.getState().bootstrap()
  }, [])

  if (phase === 'splash') return <SplashPage error={bootError} />

  return (
    <>
      <AppShell />
      <LoginSheet open={loginSheetOpen} onClose={closeLoginSheet} />
      {redPacketSheet.open && (
        <RedPacketSheet
          title={redPacketSheet.title}
          amountPhp={redPacketSheet.amountPhp}
          onClose={closeRedPacket}
        />
      )}
    </>
  )
}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/auth/google/callback" element={<GoogleAuthCallback />} />
        <Route path="*" element={<MainApp />} />
      </Routes>
    </BrowserRouter>
  )
}

// apps/web-tma/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import AppShell from '@/views/AppShell.vue'
import SplashPage from '@/views/SplashPage.vue'
import GoogleAuthCallback from '@/views/GoogleAuthCallback.vue'
import LoginSheet from '@/components/auth/LoginSheet.vue'
import RedPacketSheet from '@/components/promotion/RedPacketSheet.vue'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const { phase, bootError, loginSheetOpen } = storeToRefs(auth)

const isGoogleCallback =
  typeof window !== 'undefined' && window.location.pathname === '/auth/google/callback'

onMounted(() => {
  if (!isGoogleCallback) void auth.bootstrap()
})
</script>

<template>
  <GoogleAuthCallback v-if="isGoogleCallback" />
  <template v-else>
    <SplashPage v-if="phase === 'splash'" :error="bootError" />
    <AppShell v-else />
    <LoginSheet :open="loginSheetOpen" @close="auth.closeLoginSheet()" />
    <RedPacketSheet />
  </template>
</template>
