// apps/web-admin/src/components/AppLayout.tsx
import { useMemo, useState } from 'react'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import {
  Layout, Menu, Dropdown, Button, Modal, Form, Input, message,
} from 'antd'
import {
  DashboardOutlined, TeamOutlined, UserOutlined, DownOutlined,
  AppstoreOutlined, SettingOutlined, CustomerServiceOutlined,
  TransactionOutlined, ApartmentOutlined, SafetyCertificateOutlined,
} from '@ant-design/icons'
import { useAuthStore } from '../stores/auth'
import { adminChangePassword } from '../api'

const { Sider, Header, Content } = Layout

const menuItems = [
  { key: '/dashboard', icon: <DashboardOutlined />, label: '数据概览' },
  { key: '/users', icon: <TeamOutlined />, label: '用户管理' },
  {
    key: 'finance',
    icon: <TransactionOutlined />,
    label: '财务管理',
    children: [
      { key: '/deposits', label: '存款管理' },
      { key: '/withdrawals', label: '提款审批' },
      { key: '/sg-settlement', label: '结算对账' },
    ],
  },
  {
    key: 'review',
    icon: <SafetyCertificateOutlined />,
    label: '取款审核',
    children: [
      { key: '/review/overview', label: '审核总览' },
      { key: '/review/manual', label: '待人工处理' },
      { key: '/review/proposals', label: '提案审核记录' },
      { key: '/review/config', label: '审核规则配置' },
      { key: '/review/blacklist', label: '风控名单' },
    ],
  },
  {
    key: 'content',
    icon: <AppstoreOutlined />,
    label: '游戏内容',
    children: [
      { key: '/games', label: '游戏管理' },
      { key: '/bet-orders', label: '投注记录' },
      { key: '/promotions', label: '活动配置' },
      { key: '/promotions/claims', label: '参与记录' },
      { key: '/rebate', label: '洗码管理' },
    ],
  },
  {
    key: 'team',
    icon: <ApartmentOutlined />,
    label: '分销管理',
    children: [
      { key: '/team-referral/agents', label: '代理管理' },
      { key: '/team-referral/commissions', label: '佣金流水' },
      { key: '/team-referral/withdrawals', label: '提现审核' },
      { key: '/team-referral/config', label: '佣金配置' },
    ],
  },
  {
    key: 'cs',
    icon: <CustomerServiceOutlined />,
    label: '客服系统',
    children: [
      { key: '/customer-service', label: '客服工作台' },
      { key: '/cs-faq', label: '知识库管理' },
    ],
  },
  {
    key: 'system',
    icon: <SettingOutlined />,
    label: '系统管理',
    children: [
      { key: '/exchange-rates', label: '汇率管理' },
      { key: '/audit-log', label: '操作日志' },
      { key: '/settings', label: '系统设置' },
    ],
  },
]

function getDefaultOpenKey(pathname: string): string {
  if (pathname.startsWith('/review')) return 'review'
  if (['/deposits', '/withdrawals', '/sg-settlement'].some((p) => pathname.startsWith(p))) return 'finance'
  if (['/games', '/bet-orders', '/promotions', '/rebate'].some((p) => pathname.startsWith(p))) return 'content'
  if (pathname.startsWith('/team-referral')) return 'team'
  if (['/customer-service', '/cs-faq'].some((p) => pathname.startsWith(p))) return 'cs'
  if (['/exchange-rates', '/audit-log', '/settings'].some((p) => pathname.startsWith(p))) return 'system'
  return ''
}

export default function AppLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const { role, logout } = useAuthStore()
  const [collapsed, setCollapsed] = useState(false)
  const [showPwdModal, setShowPwdModal] = useState(false)
  const [pwdLoading, setPwdLoading] = useState(false)
  const [form] = Form.useForm<{ current: string; newPwd: string; confirm: string }>()
  const defaultOpenKeys = useMemo(() => { const k = getDefaultOpenKey(location.pathname); return k ? [k] : [] }, [])

  async function handleChangePwd() {
    const values = form.getFieldsValue()
    if (!values.current || !values.newPwd || !values.confirm) {
      message.warning('请填写所有字段'); return
    }
    if (values.newPwd !== values.confirm) {
      message.warning('两次输入的新密码不一致'); return
    }
    if (values.newPwd.length < 8) {
      message.warning('新密码至少8位'); return
    }
    setPwdLoading(true)
    try {
      await adminChangePassword(values.current, values.newPwd)
      message.success('密码已修改，请重新登录')
      setShowPwdModal(false)
      form.resetFields()
      await logout()
      navigate('/login')
    } catch (e) {
      message.error(e instanceof Error ? e.message : '修改失败')
    } finally {
      setPwdLoading(false)
    }
  }

  async function handleLogout() {
    await logout()
    message.success('已退出')
    navigate('/login')
  }

  const userMenuItems = [
    { key: 'change-pwd', label: '修改密码', onClick: () => setShowPwdModal(true) },
    { type: 'divider' as const },
    { key: 'logout', label: '退出登录', danger: true, onClick: handleLogout },
  ]

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider collapsible collapsed={collapsed} onCollapse={setCollapsed} theme="dark">
        <div style={{
          height: 64, display: 'flex', alignItems: 'center', justifyContent: 'center',
          color: '#fff', fontSize: 18, fontWeight: 'bold', background: 'rgba(255,255,255,.1)',
          marginBottom: 4,
        }}>
          {collapsed ? 'BG' : '🎰 BetoGo'}
        </div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[location.pathname]}
          defaultOpenKeys={defaultOpenKeys}
          items={menuItems}
          onClick={({ key }) => navigate(key)}
        />
      </Sider>

      <Layout>
        <Header style={{ background: '#fff', padding: '0 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', boxShadow: '0 1px 4px rgba(0,0,0,.1)' }}>
          <span style={{ fontWeight: 600, fontSize: 16 }}>BetoGo 管理后台</span>
          <Dropdown menu={{ items: userMenuItems }}>
            <Button type="text">
              <UserOutlined /> {role || 'Admin'} <DownOutlined />
            </Button>
          </Dropdown>
        </Header>

        <Content style={{ margin: 16 }}>
          <Outlet />
        </Content>
      </Layout>

      <Modal
        open={showPwdModal}
        title="修改登录密码"
        footer={null}
        onCancel={() => { setShowPwdModal(false); form.resetFields() }}
      >
        <Form form={form} layout="vertical" style={{ marginTop: 8 }}>
          <Form.Item label="当前密码" name="current">
            <Input.Password placeholder="请输入当前密码" />
          </Form.Item>
          <Form.Item label="新密码" name="newPwd">
            <Input.Password placeholder="至少8位" />
          </Form.Item>
          <Form.Item label="确认新密码" name="confirm">
            <Input.Password placeholder="再次输入新密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={pwdLoading} block onClick={handleChangePwd}>确认修改</Button>
          </Form.Item>
        </Form>
      </Modal>
    </Layout>
  )
}

// apps/web-admin/src/components/AppLayout.vue
<template>
  <a-layout style="min-height: 100vh">
    <a-layout-sider v-model:collapsed="collapsed" collapsible theme="dark">
      <div class="logo">
        <span v-if="!collapsed">🎰 BetoGo</span>
        <span v-else>BG</span>
      </div>
      <a-menu
        theme="dark"
        mode="inline"
        :selected-keys="[route.path]"
        @click="onMenuClick"
      >
        <a-menu-item key="/dashboard">
          <dashboard-outlined />
          <span>数据概览</span>
        </a-menu-item>
        <a-menu-item key="/users">
          <team-outlined />
          <span>用户管理</span>
        </a-menu-item>
        <a-menu-item key="/deposits">
          <arrow-down-outlined />
          <span>存款管理</span>
        </a-menu-item>
        <a-menu-item key="/withdrawals">
          <arrow-up-outlined />
          <span>提款审批</span>
        </a-menu-item>
        <a-menu-item key="/games">
          <appstore-outlined />
          <span>游戏管理</span>
        </a-menu-item>
        <a-menu-item key="/bet-orders">
          <transaction-outlined />
          <span>投注记录</span>
        </a-menu-item>
        <a-menu-item key="/sg-settlement">
          <reconciliation-outlined />
          <span>结算对账</span>
        </a-menu-item>
        <a-menu-item key="/team-referral">
          <apartment-outlined />
          <span>分销管理</span>
        </a-menu-item>
        <a-menu-item key="/audit-log">
          <file-text-outlined />
          <span>操作日志</span>
        </a-menu-item>
        <a-menu-item key="/customer-service">
          <customer-service-outlined />
          <span>客服工作台</span>
        </a-menu-item>
        <a-menu-item key="/cs-faq">
          <book-outlined />
          <span>知识库管理</span>
        </a-menu-item>
        <a-menu-item key="/exchange-rates">
          <swap-outlined />
          <span>汇率管理</span>
        </a-menu-item>
        <a-menu-item key="/settings">
          <setting-outlined />
          <span>系统设置</span>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>

    <a-layout>
      <a-layout-header style="background:#fff; padding: 0 16px; display:flex; align-items:center; justify-content:space-between; box-shadow: 0 1px 4px rgba(0,0,0,.1)">
        <span style="font-weight:600; font-size:16px">BetoGo 管理后台</span>
        <a-dropdown>
          <a-button type="text">
            <user-outlined /> {{ role || 'Admin' }} <down-outlined />
          </a-button>
          <template #overlay>
            <a-menu>
              <a-menu-item @click="showPwdModal = true">修改密码</a-menu-item>
              <a-menu-divider />
              <a-menu-item @click="handleLogout" style="color:red">退出登录</a-menu-item>
            </a-menu>
          </template>
        </a-dropdown>
      </a-layout-header>

      <a-layout-content style="margin: 16px">
        <RouterView />
      </a-layout-content>
    </a-layout>
  </a-layout>

  <!-- 修改密码弹窗 -->
  <a-modal v-model:open="showPwdModal" title="修改登录密码" :footer="null" @cancel="resetPwdForm">
    <a-form layout="vertical" style="margin-top:8px">
      <a-form-item label="当前密码">
        <a-input-password v-model:value="pwdForm.current" placeholder="请输入当前密码" />
      </a-form-item>
      <a-form-item label="新密码">
        <a-input-password v-model:value="pwdForm.newPwd" placeholder="至少8位" />
      </a-form-item>
      <a-form-item label="确认新密码">
        <a-input-password v-model:value="pwdForm.confirm" placeholder="再次输入新密码" />
      </a-form-item>
      <a-form-item>
        <a-button type="primary" :loading="pwdLoading" block @click="handleChangePwd">确认修改</a-button>
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute, RouterView } from 'vue-router'
import {
  DashboardOutlined, TeamOutlined, ArrowDownOutlined, ArrowUpOutlined,
  FileTextOutlined, UserOutlined, DownOutlined, AppstoreOutlined, SettingOutlined,
  CustomerServiceOutlined, BookOutlined, SwapOutlined, TransactionOutlined, ReconciliationOutlined, ApartmentOutlined,
} from '@ant-design/icons-vue'
import { useAuthStore } from '../stores/auth.js'
import { adminChangePassword } from '../api.js'
import { message } from 'ant-design-vue'

const collapsed = ref(false)
const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const role = auth.role

const showPwdModal = ref(false)
const pwdLoading = ref(false)
const pwdForm = reactive({ current: '', newPwd: '', confirm: '' })

function onMenuClick(info: { key: string }) {
  router.push(info.key)
}

function resetPwdForm() {
  pwdForm.current = ''
  pwdForm.newPwd = ''
  pwdForm.confirm = ''
}

async function handleChangePwd() {
  if (!pwdForm.current || !pwdForm.newPwd || !pwdForm.confirm) {
    message.warning('请填写所有字段'); return
  }
  if (pwdForm.newPwd !== pwdForm.confirm) {
    message.warning('两次输入的新密码不一致'); return
  }
  if (pwdForm.newPwd.length < 8) {
    message.warning('新密码至少8位'); return
  }
  pwdLoading.value = true
  try {
    await adminChangePassword(pwdForm.current, pwdForm.newPwd)
    message.success('密码已修改，请重新登录')
    showPwdModal.value = false
    resetPwdForm()
    await auth.logout()
    router.push('/login')
  } catch (e) {
    message.error(e instanceof Error ? e.message : '修改失败')
  } finally {
    pwdLoading.value = false
  }
}

async function handleLogout() {
  await auth.logout()
  message.success('已退出')
  router.push('/login')
}
</script>

<style scoped>
.logo {
  height: 64px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
  background: rgba(255,255,255,.1);
  margin-bottom: 4px;
}
</style>
