// apps/web-admin/src/views/BetOrders.tsx
import { useEffect, useState } from 'react'
import { Table, Space, Input, Select, Button, Tag, Row, Col, Statistic, DatePicker, message } from 'antd'
import type { TablePaginationConfig } from 'antd'
import type { Dayjs } from 'dayjs'
import { getBetOrders, type BetOrderRecord, type BetOrderStats } from '../api'

function betTypeColor(t: string) {
  if (t === 'bet') return 'blue'
  if (t === 'win') return 'green'
  if (t === 'refund') return 'orange'
  return 'default'
}
function betTypeLabel(t: string) {
  return ({ bet: '投注', win: '派彩', refund: '退款', cancel: '取消' } as Record<string, string>)[t] ?? t
}
function statusColor(s: string) {
  if (s === 'settled') return 'green'
  if (s === 'failed') return 'red'
  return 'default'
}
function fmtTime(t: string) {
  return new Date(t).toLocaleString('zh-CN', { hour12: false })
}

const pageSize = 20

export default function BetOrders() {
  const [loading, setLoading] = useState(false)
  const [items, setItems] = useState<BetOrderRecord[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [stats, setStats] = useState<BetOrderStats>({ totalBet: 0, totalWin: 0, roundCount: 0 })
  const [userId, setUserId] = useState('')
  const [betType, setBetType] = useState<string | undefined>()
  const [status, setStatus] = useState<string | undefined>()
  const [dateRange, setDateRange] = useState<[Dayjs | null, Dayjs | null] | null>(null)

  async function load(p = 1) {
    setLoading(true)
    try {
      const res = await getBetOrders({
        page: p, pageSize,
        userId: userId || undefined,
        betType,
        status,
        dateFrom: dateRange?.[0]?.format('YYYY-MM-DD'),
        dateTo: dateRange?.[1]?.format('YYYY-MM-DD'),
      })
      setItems(res.items); setTotal(res.total); setPage(p)
      setStats(res.stats)
    } catch (e) { message.error(e instanceof Error ? e.message : '加载失败') }
    finally { setLoading(false) }
  }

  function reset() {
    setUserId(''); setBetType(undefined); setStatus(undefined); setDateRange(null)
    setPage(1); void load(1)
  }

  useEffect(() => { void load() }, [])

  const columns = [
    { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
    { title: '用户 ID', dataIndex: 'userId', key: 'userId', width: 120, ellipsis: true },
    { title: '供应商', dataIndex: 'providerId', key: 'providerId', width: 130, ellipsis: true },
    { title: '局号', dataIndex: 'roundId', key: 'roundId', width: 130, ellipsis: true },
    { title: '类型', key: 'betType', width: 70, render: (_: unknown, r: BetOrderRecord) => <Tag color={betTypeColor(r.betType)}>{betTypeLabel(r.betType)}</Tag> },
    {
      title: '金额', key: 'amount', width: 180,
      render: (_: unknown, r: BetOrderRecord) => (
        <span>
          {r.currencyCode} {Number(r.amount).toFixed(2)}
          {r.originalAmount && r.currencyCode !== 'PHP' && <span style={{ color: '#888', fontSize: 11, marginLeft: 4 }}>(原始 {Number(r.originalAmount).toFixed(4)})</span>}
        </span>
      ),
    },
    { title: '状态', key: 'status', width: 90, render: (_: unknown, r: BetOrderRecord) => <Tag color={statusColor(r.status)}>{r.status}</Tag> },
    { title: '时间', key: 'createdAt', width: 150, render: (_: unknown, r: BetOrderRecord) => <span style={{ fontSize: 12, color: '#888' }}>{fmtTime(r.createdAt)}</span> },
  ]

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total,
    showSizeChanger: false,
    showTotal: (t) => `共 ${t} 条`,
    onChange: (p) => load(p),
  }

  return (
    <div>
      <h2 style={{ margin: '0 0 16px' }}>投注记录</h2>
      <Row gutter={16} style={{ marginBottom: 16 }}>
        <Col span={6}><Statistic title="总投注（PHP）" value={stats.totalBet.toFixed(2)} prefix="₱" /></Col>
        <Col span={6}><Statistic title="总派彩（PHP）" value={stats.totalWin.toFixed(2)} prefix="₱" /></Col>
        <Col span={6}><Statistic title="GGR（PHP）" value={(stats.totalBet - stats.totalWin).toFixed(2)} prefix="₱" valueStyle={{ color: stats.totalBet >= stats.totalWin ? '#3f8600' : '#cf1322' }} /></Col>
        <Col span={6}><Statistic title="局数" value={stats.roundCount} /></Col>
      </Row>
      <Space wrap style={{ marginBottom: 16 }}>
        <Input value={userId} onChange={(e) => setUserId(e.target.value)} placeholder="用户 ID" allowClear style={{ width: 160 }} onPressEnter={() => load(1)} />
        <Select value={betType} placeholder="类型" allowClear style={{ width: 110 }} onChange={(v) => { setBetType(v); void load(1) }} options={[
          { value: 'bet', label: '投注' }, { value: 'win', label: '派彩' }, { value: 'refund', label: '退款' }, { value: 'cancel', label: '取消' },
        ]} />
        <Select value={status} placeholder="状态" allowClear style={{ width: 110 }} onChange={(v) => { setStatus(v); void load(1) }} options={[
          { value: 'pending', label: 'pending' }, { value: 'settled', label: 'settled' }, { value: 'failed', label: 'failed' },
        ]} />
        <DatePicker.RangePicker
          value={dateRange}
          format="YYYY-MM-DD"
          style={{ width: 240 }}
          onChange={(v) => { setDateRange(v); void load(1) }}
        />
        <Button type="primary" onClick={() => load(1)}>查询</Button>
        <Button onClick={reset}>重置</Button>
      </Space>
      <Table dataSource={items} columns={columns} rowKey="id" loading={loading} pagination={pagination} size="small" />
    </div>
  )
}

// apps/web-admin/src/views/BetOrders.vue
<template>
  <div>
    <h2 style="margin:0 0 16px">投注记录</h2>

    <!-- 统计卡片 -->
    <a-row :gutter="16" style="margin-bottom:16px">
      <a-col :span="6">
        <a-statistic title="总投注（PHP）" :value="stats.totalBet.toFixed(2)" prefix="₱" />
      </a-col>
      <a-col :span="6">
        <a-statistic title="总派彩（PHP）" :value="stats.totalWin.toFixed(2)" prefix="₱" />
      </a-col>
      <a-col :span="6">
        <a-statistic
          title="GGR（PHP）"
          :value="(stats.totalBet - stats.totalWin).toFixed(2)"
          prefix="₱"
          :value-style="{ color: stats.totalBet >= stats.totalWin ? '#3f8600' : '#cf1322' }"
        />
      </a-col>
      <a-col :span="6">
        <a-statistic title="局数" :value="stats.roundCount" />
      </a-col>
    </a-row>

    <!-- 筛选 -->
    <a-space wrap style="margin-bottom:16px">
      <a-input v-model:value="filters.userId" placeholder="用户 ID" allow-clear style="width:160px" @pressEnter="load" />
      <a-select v-model:value="filters.betType" placeholder="类型" allow-clear style="width:110px" @change="load">
        <a-select-option value="bet">投注</a-select-option>
        <a-select-option value="win">派彩</a-select-option>
        <a-select-option value="refund">退款</a-select-option>
        <a-select-option value="cancel">取消</a-select-option>
      </a-select>
      <a-select v-model:value="filters.status" placeholder="状态" allow-clear style="width:110px" @change="load">
        <a-select-option value="pending">pending</a-select-option>
        <a-select-option value="settled">settled</a-select-option>
        <a-select-option value="failed">failed</a-select-option>
      </a-select>
      <a-range-picker
        v-model:value="dateRange"
        value-format="YYYY-MM-DD"
        style="width:240px"
        @change="load"
      />
      <a-button type="primary" @click="load">查询</a-button>
      <a-button @click="reset">重置</a-button>
    </a-space>

    <a-table
      :dataSource="items"
      :columns="columns"
      rowKey="id"
      :loading="loading"
      :pagination="{
        current: page,
        pageSize,
        total,
        showSizeChanger: false,
        showTotal: (t: number) => `共 ${t} 条`,
        onChange: (p: number) => { page = p; load() },
      }"
      size="small"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'betType'">
          <a-tag :color="betTypeColor(record.betType)">{{ betTypeLabel(record.betType) }}</a-tag>
        </template>
        <template v-if="column.key === 'amount'">
          <span>₱{{ Number(record.amount).toFixed(2) }}</span>
          <span v-if="record.originalAmount" style="color:#888; font-size:11px; margin-left:4px">
            ({{ record.currencyCode }} {{ Number(record.originalAmount).toFixed(4) }})
          </span>
        </template>
        <template v-if="column.key === 'status'">
          <a-tag :color="statusColor(record.status)">{{ record.status }}</a-tag>
        </template>
        <template v-if="column.key === 'createdAt'">
          <span style="font-size:12px; color:#888">{{ fmtTime(record.createdAt) }}</span>
        </template>
      </template>
    </a-table>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { getBetOrders, type BetOrderRecord, type BetOrderStats } from '../api.js'

const loading = ref(false)
const items = ref<BetOrderRecord[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = 20
const stats = reactive<BetOrderStats>({ totalBet: 0, totalWin: 0, roundCount: 0 })
const dateRange = ref<[string, string] | null>(null)

const filters = reactive({
  userId: '',
  betType: undefined as string | undefined,
  status: undefined as string | undefined,
})

const columns = [
  { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
  { title: '用户 ID', dataIndex: 'userId', key: 'userId', width: 120, ellipsis: true },
  { title: '供应商', dataIndex: 'providerId', key: 'providerId', width: 130, ellipsis: true },
  { title: '局号', dataIndex: 'roundId', key: 'roundId', width: 130, ellipsis: true },
  { title: '类型', key: 'betType', width: 70 },
  { title: '金额', key: 'amount', width: 160 },
  { title: '状态', key: 'status', width: 90 },
  { title: '时间', key: 'createdAt', width: 150 },
]

function betTypeColor(t: string) {
  if (t === 'bet') return 'blue'
  if (t === 'win') return 'green'
  if (t === 'refund') return 'orange'
  return 'default'
}
function betTypeLabel(t: string) {
  return { bet: '投注', win: '派彩', refund: '退款', cancel: '取消' }[t] ?? t
}
function statusColor(s: string) {
  if (s === 'settled') return 'green'
  if (s === 'failed') return 'red'
  return 'default'
}
function fmtTime(t: string) {
  return new Date(t).toLocaleString('zh-CN', { hour12: false })
}

async function load() {
  loading.value = true
  try {
    const res = await getBetOrders({
      page: page.value,
      pageSize,
      userId: filters.userId || undefined,
      betType: filters.betType,
      status: filters.status,
      dateFrom: dateRange.value?.[0],
      dateTo: dateRange.value?.[1],
    })
    items.value = res.items
    total.value = res.total
    Object.assign(stats, res.stats)
  } catch (e) {
    message.error(e instanceof Error ? e.message : '加载失败')
  } finally {
    loading.value = false
  }
}

function reset() {
  filters.userId = ''
  filters.betType = undefined
  filters.status = undefined
  dateRange.value = null
  page.value = 1
  load()
}

onMounted(load)
</script>
