// apps/web-admin/src/views/Games.vue
<template>
  <div>
    <a-space style="margin-bottom:12px;width:100%;justify-content:space-between" align="center">
      <h2 style="margin:0">游戏管理</h2>
      <a-space>
        <a-button :loading="translating" @click="doTranslate">AI 翻译游戏名</a-button>
        <a-button type="primary" :loading="syncing" @click="doSync">同步游戏库</a-button>
      </a-space>
    </a-space>

    <!-- 筛选栏 -->
    <div style="background:#fafafa;border:1px solid #f0f0f0;border-radius:6px;padding:12px 16px;margin-bottom:14px">
      <a-row :gutter="[8, 8]">
        <a-col :span="5">
          <a-input-search v-model:value="search" placeholder="搜索游戏名/关键词" @search="load(1)" allow-clear />
        </a-col>
        <a-col :span="4">
          <a-select v-model:value="providerFilter" placeholder="游戏商" allow-clear style="width:100%" @change="load(1)">
            <a-select-option v-for="p in providers" :key="p" :value="p">{{ p }}</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="sortCategoryFilter" placeholder="前端分类" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="slots">Slots</a-select-option>
            <a-select-option value="fishing">Fishing</a-select-option>
            <a-select-option value="live">Live</a-select-option>
            <a-select-option value="bingo">Bingo</a-select-option>
            <a-select-option value="crash">Crash</a-select-option>
            <a-select-option value="table">Table</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="themeFilter" placeholder="游戏主题" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="fishing">fishing</a-select-option>
            <a-select-option value="asian">asian</a-select-option>
            <a-select-option value="mythology">mythology</a-select-option>
            <a-select-option value="fantasy">fantasy</a-select-option>
            <a-select-option value="adventure">adventure</a-select-option>
            <a-select-option value="fruit">fruit</a-select-option>
            <a-select-option value="classic">classic</a-select-option>
            <a-select-option value="animal">animal</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="gameStyleFilter" placeholder="游戏风格" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="asian">asian</a-select-option>
            <a-select-option value="western">western</a-select-option>
            <a-select-option value="classic">classic</a-select-option>
            <a-select-option value="modern">modern</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="playerTypeFilter" placeholder="适合玩家" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="casual">casual 休闲</a-select-option>
            <a-select-option value="regular">regular 普通</a-select-option>
            <a-select-option value="high-roller">high-roller 高额</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="weightRangeFilter" placeholder="权重分段" allow-clear style="width:100%" @change="onWeightRangeChange">
            <a-select-option value="80-100">高热度 80-100</a-select-option>
            <a-select-option value="50-79">中热度 50-79</a-select-option>
            <a-select-option value="1-49">低热度 1-49</a-select-option>
            <a-select-option value="0-0">未评分 0</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="volatilityFilter" placeholder="波动性" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="low">低 Low</a-select-option>
            <a-select-option value="medium">中 Medium</a-select-option>
            <a-select-option value="high">高 High</a-select-option>
            <a-select-option value="very-high">极高 Very High</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="demoFilter" placeholder="支持试玩" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="true">支持试玩</a-select-option>
            <a-select-option value="false">不支持</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="featuredFilter" placeholder="推荐首页" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="true">已推荐</a-select-option>
            <a-select-option value="false">未推荐</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="techFilter" placeholder="技术" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="HTML5">HTML5</a-select-option>
            <a-select-option value="Flash">Flash</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3">
          <a-select v-model:value="activeFilter" placeholder="状态" allow-clear style="width:100%" @change="load(1)">
            <a-select-option value="true">已启用</a-select-option>
            <a-select-option value="false">已禁用</a-select-option>
          </a-select>
        </a-col>
        <a-col :span="3" style="display:flex;align-items:center;gap:8px">
          <a-tag color="blue">共 {{ total }} 款</a-tag>
          <a-button size="small" @click="resetFilters">重置</a-button>
        </a-col>
      </a-row>
    </div>

    <a-table
      :columns="columns"
      :data-source="games"
      :loading="loading"
      :pagination="pagination"
      row-key="uuid"
      size="small"
      :scroll="{ x: 1400 }"
      @change="onTableChange"
    >
      <template #bodyCell="{ column, record }">
        <!-- 游戏名 -->
        <template v-if="column.key === 'name'">
          <div style="display:flex;gap:8px;align-items:flex-start">
            <img
              v-if="record.imageHqUrl || record.imageUrl"
              :src="record.imageHqUrl || record.imageUrl"
              style="width:32px;height:32px;object-fit:cover;border-radius:4px;flex-shrink:0;margin-top:2px"
            />
            <div style="min-width:0">
              <div style="font-weight:500;line-height:1.4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">
                {{ record.name }}
              </div>
              <div style="display:flex;gap:3px;flex-wrap:wrap;margin-top:2px">
                <a-tag v-if="record.isFeatured" color="gold" style="font-size:10px;padding:0 3px;line-height:16px;margin:0">推荐</a-tag>
                <a-tag v-if="record.hasDemo" color="blue" style="font-size:10px;padding:0 3px;line-height:16px;margin:0">Demo</a-tag>
                <a-tag v-if="record.isMobile" color="green" style="font-size:10px;padding:0 3px;line-height:16px;margin:0">手机</a-tag>
              </div>
            </div>
          </div>
        </template>

        <!-- 游戏商 -->
        <template v-if="column.key === 'provider'">
          <div style="font-size:13px">{{ record.provider }}</div>
          <div v-if="record.label" style="font-size:11px;color:#888;margin-top:1px">{{ record.label }}</div>
          <a-tag v-if="record.technology" :color="record.technology === 'HTML5' ? 'blue' : 'orange'"
            style="font-size:10px;padding:0 4px;margin-top:2px">{{ record.technology }}</a-tag>
        </template>

        <!-- 前端分类 -->
        <template v-if="column.key === 'sortCategory'">
          <a-tag v-if="record.sortCategory" :color="sortCategoryColor(record.sortCategory)"
            style="font-size:11px;margin-bottom:2px">{{ record.sortCategory }}</a-tag>
          <div v-else style="color:#ccc;font-size:12px">—</div>
          <div style="font-size:11px;color:#aaa">{{ record.type || record.category || '' }}</div>
        </template>

        <!-- 主题/风格/玩家 -->
        <template v-if="column.key === 'aiAttrs'">
          <div v-if="record.theme" style="font-size:11px;color:#595959">
            <span style="color:#999">主题:</span> {{ record.theme }}
          </div>
          <div v-if="record.gameStyle" style="font-size:11px;color:#595959;margin-top:1px">
            <span style="color:#999">风格:</span> {{ record.gameStyle }}
          </div>
          <div v-if="record.playerType" style="font-size:11px;margin-top:1px">
            <a-tag :color="playerTypeColor(record.playerType)" style="font-size:10px;padding:0 4px">{{ record.playerType }}</a-tag>
          </div>
          <div v-if="!record.theme && !record.gameStyle && !record.playerType" style="color:#ccc;font-size:12px">—</div>
        </template>

        <!-- 参数 -->
        <template v-if="column.key === 'params'">
          <div v-if="record.rtp != null" style="font-size:12px">RTP <b>{{ record.rtp }}%</b></div>
          <a-tag v-if="record.volatility" :color="volatilityColor(record.volatility)"
            style="font-size:10px;padding:0 4px;margin-top:2px">{{ record.volatility }}</a-tag>
          <div v-if="record.reelsCount || record.linesCount" style="font-size:10px;color:#aaa;margin-top:2px">
            <span v-if="record.reelsCount">{{ record.reelsCount }}轮</span>
            <span v-if="record.reelsCount && record.linesCount"> · </span>
            <span v-if="record.linesCount">{{ record.linesCount }}线</span>
          </div>
        </template>

        <!-- 权重长条 -->
        <template v-if="column.key === 'weight'">
          <div v-if="record.weight > 0" style="display:flex;align-items:center;gap:4px">
            <a-progress
              type="line"
              :percent="record.weight"
              :stroke-width="8"
              :stroke-color="weightColor(record.weight)"
              :show-info="false"
              style="flex:1;min-width:50px;margin:0"
            />
            <span style="font-size:11px;color:#595959;width:22px;text-align:right;flex-shrink:0">{{ record.weight }}</span>
          </div>
          <span v-else style="color:#d9d9d9;font-size:11px">未评</span>
        </template>

        <!-- PH热度 -->
        <template v-if="column.key === 'phBonus'">
          <span v-if="record.phBonus > 0" style="font-size:13px;font-weight:600;color:#1677ff">{{ record.phBonus }}</span>
          <span v-else style="color:#d9d9d9;font-size:11px">—</span>
          <span v-if="record.phBonus > 0" style="font-size:10px;color:#999"> /30</span>
        </template>

        <!-- 特性 -->
        <template v-if="column.key === 'features'">
          <a-space wrap :size="2">
            <a-tag v-if="record.hasFreespins" color="purple" style="font-size:10px;padding:0 4px">免费旋</a-tag>
            <a-tag v-if="record.hasLobby" color="cyan" style="font-size:10px;padding:0 4px">大厅</a-tag>
            <a-tag v-if="record.hasTables" color="geekblue" style="font-size:10px;padding:0 4px">桌台</a-tag>
          </a-space>
          <div v-if="!record.hasFreespins && !record.hasLobby && !record.hasTables" style="color:#ccc;font-size:11px">—</div>
        </template>

        <!-- 操作 -->
        <template v-if="column.key === 'actions'">
          <div style="display:flex;flex-direction:column;align-items:center;gap:4px">
            <a-switch
              :checked="record.isActive"
              size="small"
              :loading="togglingUuid === record.uuid"
              @change="(val: boolean) => onToggle(record, val)"
            />
            <a-button type="link" size="small" style="padding:0;height:auto;font-size:11px" @click="openDetail(record)">
              详情
            </a-button>
          </div>
        </template>
      </template>
    </a-table>

    <!-- 详情弹窗 -->
    <a-modal
      v-model:open="detailVisible"
      :title="detailGame?.name"
      :footer="null"
      width="680px"
      :body-style="{ maxHeight: '75vh', overflowY: 'auto', padding: '16px 20px' }"
      destroy-on-close
    >
      <template v-if="detailGame">
        <!-- 封面图 -->
        <div v-if="detailGame.imageHqUrl || detailGame.imageUrl" style="text-align:center;margin-bottom:14px">
          <img
            :src="detailGame.imageHqUrl || detailGame.imageUrl || ''"
            style="max-width:100%;max-height:160px;object-fit:contain;border-radius:6px"
          />
        </div>

        <!-- 基本信息 -->
        <a-descriptions title="基本信息" :column="2" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="UUID" :span="2">
            <span style="font-size:11px;font-family:monospace;word-break:break-all">{{ detailGame.uuid }}</span>
          </a-descriptions-item>
          <a-descriptions-item label="游戏商">
            {{ detailGame.provider }}
            <span v-if="detailGame.providerId" style="color:#999;font-size:11px"> (ID: {{ detailGame.providerId }})</span>
          </a-descriptions-item>
          <a-descriptions-item label="子标签">{{ detailGame.label || '—' }}</a-descriptions-item>
          <a-descriptions-item label="技术">
            <a-tag v-if="detailGame.technology" :color="detailGame.technology === 'HTML5' ? 'blue' : 'orange'">{{ detailGame.technology }}</a-tag>
            <span v-else>—</span>
          </a-descriptions-item>
          <a-descriptions-item label="状态">
            <a-tag :color="detailGame.isActive ? 'green' : 'red'">{{ detailGame.isActive ? '已启用' : '已禁用' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="更新时间" :span="2">
            {{ detailGame.updatedAt ? new Date(detailGame.updatedAt).toLocaleString('zh-CN') : '—' }}
          </a-descriptions-item>
        </a-descriptions>

        <!-- 分类信息 -->
        <a-descriptions title="分类信息" :column="2" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="前端分类">
            <a-tag v-if="detailGame.sortCategory" :color="sortCategoryColor(detailGame.sortCategory)">{{ detailGame.sortCategory }}</a-tag>
            <span v-else>—</span>
          </a-descriptions-item>
          <a-descriptions-item label="游戏类型">{{ detailGame.type || '—' }}</a-descriptions-item>
          <a-descriptions-item label="分类">{{ detailGame.category || '—' }}</a-descriptions-item>
          <a-descriptions-item label="子分类">{{ detailGame.subCategory || '—' }}</a-descriptions-item>
          <a-descriptions-item label="游戏主题">{{ detailGame.theme || '—' }}</a-descriptions-item>
          <a-descriptions-item label="游戏风格">{{ detailGame.gameStyle || '—' }}</a-descriptions-item>
          <a-descriptions-item label="适合玩家" :span="2">
            <a-tag v-if="detailGame.playerType" :color="playerTypeColor(detailGame.playerType)">{{ detailGame.playerType }}</a-tag>
            <span v-else>—</span>
          </a-descriptions-item>
        </a-descriptions>

        <!-- 游戏参数 -->
        <a-descriptions title="游戏参数" :column="2" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="RTP">{{ detailGame.rtp != null ? detailGame.rtp + '%' : '—' }}</a-descriptions-item>
          <a-descriptions-item label="波动性">
            <a-tag v-if="detailGame.volatility" :color="volatilityColor(detailGame.volatility)">{{ detailGame.volatility }}</a-tag>
            <span v-else>—</span>
          </a-descriptions-item>
          <a-descriptions-item label="转轮数">{{ detailGame.reelsCount || '—' }}</a-descriptions-item>
          <a-descriptions-item label="赔付线">{{ detailGame.linesCount ?? '—' }}</a-descriptions-item>
        </a-descriptions>

        <!-- 多语言名称 -->
        <a-descriptions title="多语言名称" :column="1" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="英语 (en)">{{ detailGame.name }}</a-descriptions-item>
          <a-descriptions-item label="印尼语 (id)">
            <span v-if="detailGame.nameId">{{ detailGame.nameId }}</span>
            <span v-else style="color:#bbb">未翻译</span>
          </a-descriptions-item>
          <a-descriptions-item label="越南语 (vi)">
            <span v-if="detailGame.nameVi">{{ detailGame.nameVi }}</span>
            <span v-else style="color:#bbb">未翻译</span>
          </a-descriptions-item>
          <a-descriptions-item label="中文 (zh-CN)">
            <span v-if="detailGame.nameZh">{{ detailGame.nameZh }}</span>
            <span v-else style="color:#bbb">未翻译</span>
          </a-descriptions-item>
        </a-descriptions>

        <!-- AI 富化 -->
        <a-descriptions title="AI 富化数据" :column="1" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="热度权重">
            <div style="display:flex;align-items:center;gap:8px">
              <a-progress type="line" :percent="detailGame.weight" :stroke-width="8"
                :stroke-color="weightColor(detailGame.weight)" :show-info="false" style="flex:1;margin:0" />
              <span style="font-size:13px;font-weight:500;width:30px">{{ detailGame.weight }}</span>
            </div>
          </a-descriptions-item>
          <a-descriptions-item label="PH热度(ph_bonus)">
            <span style="font-size:13px;font-weight:500;color:#1677ff">{{ detailGame.phBonus }}</span>
            <span style="font-size:11px;color:#999"> / 30</span>
          </a-descriptions-item>
          <a-descriptions-item label="推荐首页">
            <a-tag :color="detailGame.isFeatured ? 'gold' : 'default'">{{ detailGame.isFeatured ? '已推荐' : '未推荐' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="中文简介">
            <span style="white-space:pre-wrap">{{ detailGame.descriptionZh || '—' }}</span>
          </a-descriptions-item>
          <a-descriptions-item label="英文简介">
            <span style="white-space:pre-wrap;font-size:12px">{{ detailGame.descriptionEn || '—' }}</span>
          </a-descriptions-item>
          <a-descriptions-item label="搜索关键词">
            <span style="font-size:11px;word-break:break-all">{{ detailGame.searchKeywords || '—' }}</span>
          </a-descriptions-item>
          <a-descriptions-item label="权重更新时间">
            {{ detailGame.weightUpdatedAt ? new Date(detailGame.weightUpdatedAt).toLocaleString('zh-CN') : '—' }}
          </a-descriptions-item>
        </a-descriptions>

        <!-- 功能特性 -->
        <a-descriptions title="功能特性" :column="2" bordered size="small" style="margin-bottom:14px">
          <a-descriptions-item label="支持试玩">
            <a-tag :color="detailGame.hasDemo ? 'blue' : 'default'">{{ detailGame.hasDemo ? '支持' : '不支持' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="手机端">
            <a-tag :color="detailGame.isMobile ? 'green' : 'default'">{{ detailGame.isMobile ? '支持' : '不支持' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="免费旋转">
            <a-tag :color="detailGame.hasFreespins ? 'purple' : 'default'">{{ detailGame.hasFreespins ? '支持' : '不支持' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="大厅模式">
            <a-tag :color="detailGame.hasLobby ? 'cyan' : 'default'">{{ detailGame.hasLobby ? '支持' : '不支持' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="桌台" :span="2">
            <a-tag :color="detailGame.hasTables ? 'geekblue' : 'default'">{{ detailGame.hasTables ? '有' : '无' }}</a-tag>
          </a-descriptions-item>
          <a-descriptions-item v-if="detailGame.tags?.length" label="标签" :span="2">
            <a-tag v-for="t in detailGame.tags" :key="t" style="margin:2px">{{ t }}</a-tag>
          </a-descriptions-item>
        </a-descriptions>

        <!-- 图片地址 -->
        <a-descriptions title="图片" :column="1" bordered size="small">
          <a-descriptions-item label="标准图">
            <a v-if="detailGame.imageUrl" :href="detailGame.imageUrl" target="_blank"
              style="font-size:11px;word-break:break-all">{{ detailGame.imageUrl }}</a>
            <span v-else style="color:#ccc">—</span>
          </a-descriptions-item>
          <a-descriptions-item label="高清图">
            <a v-if="detailGame.imageHqUrl" :href="detailGame.imageHqUrl" target="_blank"
              style="font-size:11px;word-break:break-all">{{ detailGame.imageHqUrl }}</a>
            <span v-else style="color:#ccc">—</span>
          </a-descriptions-item>
        </a-descriptions>
      </template>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { getAdminGames, toggleGame, syncGames, translateGames, type AdminGame } from '../api.js'

const search = ref('')
const providerFilter = ref<string | undefined>()
const sortCategoryFilter = ref<string | undefined>()
const themeFilter = ref<string | undefined>()
const gameStyleFilter = ref<string | undefined>()
const playerTypeFilter = ref<string | undefined>()
const weightRangeFilter = ref<string | undefined>()
const volatilityFilter = ref<string | undefined>()
const demoFilter = ref<string | undefined>()
const featuredFilter = ref<string | undefined>()
const techFilter = ref<string | undefined>()
const activeFilter = ref<string | undefined>()

const loading = ref(false)
const syncing = ref(false)
const translating = ref(false)
const games = ref<AdminGame[]>([])
const providers = ref<string[]>([])
const total = ref(0)
const page = ref(1)
const sortField = ref<string | undefined>()
const sortOrder = ref<'asc' | 'desc' | undefined>()
const togglingUuid = ref<string | null>(null)
const detailVisible = ref(false)
const detailGame = ref<AdminGame | null>(null)

const pagination = computed(() => ({
  current: page.value,
  pageSize: 20,
  total: total.value,
  showTotal: (t: number) => `共 ${t} 款`,
  showSizeChanger: false,
}))

function onTableChange(
  pag: { current?: number },
  _filters: unknown,
  sorter: { columnKey?: string; order?: string },
) {
  if (sorter.columnKey && sorter.order) {
    sortField.value = sorter.columnKey
    sortOrder.value = sorter.order === 'ascend' ? 'asc' : 'desc'
  } else {
    sortField.value = undefined
    sortOrder.value = undefined
  }
  load(pag.current ?? 1)
}

function volatilityColor(v: string) {
  if (v.includes('very')) return 'magenta'
  if (v.includes('high')) return 'red'
  if (v.includes('medium')) return 'orange'
  return 'green'
}

function sortCategoryColor(cat: string) {
  const map: Record<string, string> = {
    slots: 'purple', fishing: 'cyan', live: 'red',
    bingo: 'green', crash: 'orange', table: 'blue',
  }
  return map[cat] ?? 'default'
}

function playerTypeColor(pt: string) {
  if (pt === 'high-roller') return 'red'
  if (pt === 'regular') return 'blue'
  return 'green'
}

function weightColor(w: number) {
  if (w >= 80) return '#52c41a'
  if (w >= 50) return '#faad14'
  return '#1677ff'
}

function onWeightRangeChange() { load(1) }

function resetFilters() {
  search.value = ''
  providerFilter.value = undefined
  sortCategoryFilter.value = undefined
  themeFilter.value = undefined
  gameStyleFilter.value = undefined
  playerTypeFilter.value = undefined
  weightRangeFilter.value = undefined
  volatilityFilter.value = undefined
  demoFilter.value = undefined
  featuredFilter.value = undefined
  techFilter.value = undefined
  activeFilter.value = undefined
  load(1)
}

const columns = [
  { title: '游戏', key: 'name', width: 220 },
  { title: '游戏商', key: 'provider', width: 130 },
  { title: '前端分类', key: 'sortCategory', width: 100 },
  { title: '主题/风格/玩家', key: 'aiAttrs', width: 150 },
  { title: '参数', key: 'params', width: 110 },
  { title: '热度权重', key: 'weight', width: 120, sorter: true, sortDirections: ['ascend', 'descend'] },
  { title: 'PH热度', key: 'phBonus', width: 90, sorter: true, sortDirections: ['ascend', 'descend'] },
  { title: '特性', key: 'features', width: 120 },
  { title: '操作', key: 'actions', width: 65, fixed: 'right' },
]

async function load(p = 1) {
  page.value = p
  loading.value = true
  try {
    const isActive = activeFilter.value !== undefined ? activeFilter.value === 'true' : undefined
    const isFeatured = featuredFilter.value !== undefined ? featuredFilter.value === 'true' : undefined
    const hasDemo = demoFilter.value !== undefined ? demoFilter.value === 'true' : undefined

    let weightMin: number | undefined
    let weightMax: number | undefined
    if (weightRangeFilter.value) {
      const [mn, mx] = weightRangeFilter.value.split('-').map(Number)
      weightMin = mn
      weightMax = mx
    }

    const res = await getAdminGames({
      page: p, pageSize: 20,
      provider: providerFilter.value,
      search: search.value || undefined,
      isActive,
      sortCategory: sortCategoryFilter.value,
      volatility: volatilityFilter.value,
      isFeatured,
      hasDemo,
      theme: themeFilter.value,
      gameStyle: gameStyleFilter.value,
      playerType: playerTypeFilter.value,
      weightMin,
      weightMax,
      sortField: sortField.value,
      sortOrder: sortOrder.value,
    })
    games.value = res.items
    total.value = res.total
    if (res.providers.length) providers.value = res.providers
  } finally {
    loading.value = false
  }
}

async function onToggle(record: AdminGame, val: boolean) {
  togglingUuid.value = record.uuid
  try {
    await toggleGame(record.uuid, val)
    record.isActive = val
    message.success(val ? '已启用' : '已禁用')
  } catch {
    message.error('操作失败')
  } finally {
    togglingUuid.value = null
  }
}

function openDetail(record: AdminGame) {
  detailGame.value = record
  detailVisible.value = true
}

async function doSync() {
  syncing.value = true
  try {
    const res = await syncGames()
    message.success(`同步完成，共 ${res.synced} 款游戏`)
    load(1)
  } catch (e) {
    message.error(e instanceof Error ? e.message : '同步失败')
  } finally {
    syncing.value = false
  }
}

async function doTranslate() {
  translating.value = true
  try {
    const res = await translateGames()
    if (res.total === 0) {
      message.info('所有游戏名称已翻译，无需重复操作')
    } else {
      message.success(`翻译完成：${res.translated} 款成功，${res.errors} 款失败（共 ${res.total} 款待翻译）`)
      load(1)
    }
  } catch (e) {
    message.error(e instanceof Error ? e.message : 'AI 翻译失败')
  } finally {
    translating.value = false
  }
}

onMounted(load)
</script>

// apps/web-admin/src/views/Games.tsx
import { useEffect, useState } from 'react'
import { Table, Space, Input, Select, Button, Tag, Switch, Modal, Progress, Spin, Row, Col, Descriptions, message } from 'antd'
import type { TablePaginationConfig, TableProps } from 'antd'
import {
  getAdminGames, toggleGame, startSyncGames, startTranslateGames, getGameJob,
  type AdminGame, type AdminGameJob,
} from '../api'

function volatilityColor(v: string) {
  if (v.includes('very')) return 'magenta'
  if (v.includes('high')) return 'red'
  if (v.includes('medium')) return 'orange'
  return 'green'
}
function sortCategoryColor(cat: string) {
  const m: Record<string, string> = { slots: 'purple', fishing: 'cyan', live: 'red', bingo: 'green', crash: 'orange', table: 'blue' }
  return m[cat] ?? 'default'
}
function playerTypeColor(pt: string) {
  if (pt === 'high-roller') return 'red'
  if (pt === 'regular') return 'blue'
  return 'green'
}
function weightColor(w: number) {
  if (w >= 80) return '#52c41a'
  if (w >= 50) return '#faad14'
  return '#1677ff'
}

function sleep(ms: number) { return new Promise((r) => setTimeout(r, ms)) }

export default function Games() {
  const [search, setSearch] = useState('')
  const [providerFilter, setProviderFilter] = useState<string | undefined>()
  const [sortCategoryFilter, setSortCategoryFilter] = useState<string | undefined>()
  const [themeFilter, setThemeFilter] = useState<string | undefined>()
  const [gameStyleFilter, setGameStyleFilter] = useState<string | undefined>()
  const [playerTypeFilter, setPlayerTypeFilter] = useState<string | undefined>()
  const [weightRangeFilter, setWeightRangeFilter] = useState<string | undefined>()
  const [volatilityFilter, setVolatilityFilter] = useState<string | undefined>()
  const [demoFilter, setDemoFilter] = useState<string | undefined>()
  const [featuredFilter, setFeaturedFilter] = useState<string | undefined>()
  const [techFilter, setTechFilter] = useState<string | undefined>()
  const [activeFilter, setActiveFilter] = useState<string | undefined>()
  const [loading, setLoading] = useState(false)
  const [syncing, setSyncing] = useState(false)
  const [translating, setTranslating] = useState(false)
  const [games, setGames] = useState<AdminGame[]>([])
  const [providers, setProviders] = useState<string[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [sortField, setSortField] = useState<string | undefined>()
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc' | undefined>()
  const [togglingUuid, setTogglingUuid] = useState<string | null>(null)
  const [detailVisible, setDetailVisible] = useState(false)
  const [detailGame, setDetailGame] = useState<AdminGame | null>(null)
  const [jobModal, setJobModal] = useState({ visible: false, title: '', msg: '', total: 0, percent: 0, closable: false, status: 'active' as 'active' | 'success' | 'exception' })

  async function load(p = 1) {
    setPage(p); setLoading(true)
    try {
      const isActive = activeFilter !== undefined ? activeFilter === 'true' : undefined
      const isFeatured = featuredFilter !== undefined ? featuredFilter === 'true' : undefined
      const hasDemo = demoFilter !== undefined ? demoFilter === 'true' : undefined
      let weightMin: number | undefined, weightMax: number | undefined
      if (weightRangeFilter) {
        const [mn, mx] = weightRangeFilter.split('-').map(Number)
        weightMin = mn; weightMax = mx
      }
      const res = await getAdminGames({
        page: p, pageSize: 20,
        provider: providerFilter, search: search || undefined,
        isActive, sortCategory: sortCategoryFilter, volatility: volatilityFilter,
        isFeatured, hasDemo, theme: themeFilter, gameStyle: gameStyleFilter, playerType: playerTypeFilter,
        weightMin, weightMax, sortField, sortOrder,
      })
      setGames(res.items); setTotal(res.total)
      if (res.providers.length) setProviders(res.providers)
    } finally { setLoading(false) }
  }

  useEffect(() => { void load() }, [])

  function resetFilters() {
    setSearch(''); setProviderFilter(undefined); setSortCategoryFilter(undefined); setThemeFilter(undefined)
    setGameStyleFilter(undefined); setPlayerTypeFilter(undefined); setWeightRangeFilter(undefined)
    setVolatilityFilter(undefined); setDemoFilter(undefined); setFeaturedFilter(undefined)
    setTechFilter(undefined); setActiveFilter(undefined)
    void load(1)
  }

  async function onToggle(record: AdminGame, val: boolean) {
    setTogglingUuid(record.uuid)
    try {
      await toggleGame(record.uuid, val)
      setGames((prev) => prev.map((g) => g.uuid === record.uuid ? { ...g, isActive: val } : g))
      message.success(val ? '已启用' : '已禁用')
    } catch { message.error('操作失败') }
    finally { setTogglingUuid(null) }
  }

  async function pollGameJob(jobId: string, onUpdate: (j: AdminGameJob) => void): Promise<AdminGameJob> {
    for (let i = 0; i < 3600; i++) {
      const job = await getGameJob(jobId)
      onUpdate(job)
      if (job.status === 'done' || job.status === 'failed') return job
      await sleep(2000)
    }
    throw new Error('任务超时')
  }

  async function runBatchJob(kind: 'sync' | 'translate', start: () => Promise<{ jobId: string; alreadyRunning?: boolean }>) {
    const isSync = kind === 'sync'
    if (isSync) setSyncing(true); else setTranslating(true)
    setJobModal({ visible: true, title: isSync ? '同步游戏库' : 'AI 翻译游戏名', msg: '正在启动任务…', total: 0, percent: 0, closable: false, status: 'active' })
    try {
      const { jobId, alreadyRunning } = await start()
      if (alreadyRunning) message.info('已有任务在运行，继续跟踪进度')
      const final = await pollGameJob(jobId, (job) => {
        setJobModal((m) => ({
          ...m,
          msg: job.message || '处理中…',
          total: job.total,
          percent: job.total > 0 ? Math.min(100, Math.round((job.progress / job.total) * 100)) : 0,
        }))
      })
      if (final.status === 'failed') {
        setJobModal((m) => ({ ...m, status: 'exception', closable: true }))
        message.error(final.error ?? '任务失败'); return
      }
      setJobModal((m) => ({ ...m, status: 'success', closable: true }))
      if (isSync) {
        message.success(`同步完成，共 ${final.result?.synced ?? 0} 款游戏`); void load(1)
      } else {
        const r = final.result
        const t = r?.total ?? 0
        if (t === 0) message.info('所有游戏名称已翻译，无需重复操作')
        else { message.success(`翻译完成：${r?.translated ?? 0} 款成功，${r?.errors ?? 0} 款失败（共 ${t} 款待翻译）`); void load(1) }
      }
    } catch (e) {
      setJobModal((m) => ({ ...m, status: 'exception', closable: true }))
      message.error(e instanceof Error ? e.message : '操作失败')
    } finally {
      if (isSync) setSyncing(false); else setTranslating(false)
    }
  }

  const handleTableChange: TableProps<AdminGame>['onChange'] = (pag, _filters, sorter) => {
    const s = Array.isArray(sorter) ? sorter[0] : sorter
    if (s.columnKey && s.order) {
      setSortField(String(s.columnKey))
      setSortOrder(s.order === 'ascend' ? 'asc' : 'desc')
    } else {
      setSortField(undefined); setSortOrder(undefined)
    }
    void load(pag.current ?? 1)
  }

  const columns = [
    {
      title: '游戏', key: 'name', width: 220,
      render: (_: unknown, r: AdminGame) => (
        <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
          {(r.imageHqUrl || r.imageUrl) && <img src={r.imageHqUrl || r.imageUrl || ''} style={{ width: 32, height: 32, objectFit: 'cover', borderRadius: 4, flexShrink: 0, marginTop: 2 }} />}
          <div style={{ minWidth: 0 }}>
            <div style={{ fontWeight: 500, lineHeight: 1.4, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r.name}</div>
            <div style={{ display: 'flex', gap: 3, flexWrap: 'wrap', marginTop: 2 }}>
              {r.isFeatured && <Tag color="gold" style={{ fontSize: 10, padding: '0 3px', lineHeight: '16px', margin: 0 }}>推荐</Tag>}
              {r.hasDemo && <Tag color="blue" style={{ fontSize: 10, padding: '0 3px', lineHeight: '16px', margin: 0 }}>Demo</Tag>}
              {r.isMobile && <Tag color="green" style={{ fontSize: 10, padding: '0 3px', lineHeight: '16px', margin: 0 }}>手机</Tag>}
            </div>
          </div>
        </div>
      ),
    },
    {
      title: '游戏商', key: 'provider', width: 130,
      render: (_: unknown, r: AdminGame) => (
        <div>
          <div style={{ fontSize: 13 }}>{r.provider}</div>
          {r.label && <div style={{ fontSize: 11, color: '#888', marginTop: 1 }}>{r.label}</div>}
          {r.technology && <Tag color={r.technology === 'HTML5' ? 'blue' : 'orange'} style={{ fontSize: 10, padding: '0 4px', marginTop: 2 }}>{r.technology}</Tag>}
        </div>
      ),
    },
    {
      title: '前端分类', key: 'sortCategory', width: 100,
      render: (_: unknown, r: AdminGame) => r.sortCategory
        ? <><Tag color={sortCategoryColor(r.sortCategory)} style={{ fontSize: 11, marginBottom: 2 }}>{r.sortCategory}</Tag><div style={{ fontSize: 11, color: '#aaa' }}>{r.type || r.category || ''}</div></>
        : <div style={{ color: '#ccc', fontSize: 12 }}>—</div>,
    },
    {
      title: '主题/风格/玩家', key: 'aiAttrs', width: 150,
      render: (_: unknown, r: AdminGame) => (r.theme || r.gameStyle || r.playerType) ? (
        <div>
          {r.theme && <div style={{ fontSize: 11, color: '#595959' }}><span style={{ color: '#999' }}>主题:</span> {r.theme}</div>}
          {r.gameStyle && <div style={{ fontSize: 11, color: '#595959', marginTop: 1 }}><span style={{ color: '#999' }}>风格:</span> {r.gameStyle}</div>}
          {r.playerType && <div style={{ fontSize: 11, marginTop: 1 }}><Tag color={playerTypeColor(r.playerType)} style={{ fontSize: 10, padding: '0 4px' }}>{r.playerType}</Tag></div>}
        </div>
      ) : <div style={{ color: '#ccc', fontSize: 12 }}>—</div>,
    },
    {
      title: '参数', key: 'params', width: 110,
      render: (_: unknown, r: AdminGame) => (
        <div>
          {r.rtp != null && <div style={{ fontSize: 12 }}>RTP <b>{r.rtp}%</b></div>}
          {r.volatility && <Tag color={volatilityColor(r.volatility)} style={{ fontSize: 10, padding: '0 4px', marginTop: 2 }}>{r.volatility}</Tag>}
          {(r.reelsCount || r.linesCount) && <div style={{ fontSize: 10, color: '#aaa', marginTop: 2 }}>{r.reelsCount && `${r.reelsCount}轮`}{r.reelsCount && r.linesCount && ' · '}{r.linesCount && `${r.linesCount}线`}</div>}
        </div>
      ),
    },
    {
      title: '热度权重', key: 'weight', width: 120, sorter: true, sortDirections: ['ascend' as const, 'descend' as const],
      render: (_: unknown, r: AdminGame) => r.weight > 0 ? (
        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <Progress type="line" percent={r.weight} strokeWidth={8} strokeColor={weightColor(r.weight)} showInfo={false} style={{ flex: 1, minWidth: 50, margin: 0 }} />
          <span style={{ fontSize: 11, color: '#595959', width: 22, textAlign: 'right', flexShrink: 0 }}>{r.weight}</span>
        </div>
      ) : <span style={{ color: '#d9d9d9', fontSize: 11 }}>未评</span>,
    },
    {
      title: 'PH热度', key: 'phBonus', width: 90, sorter: true, sortDirections: ['ascend' as const, 'descend' as const],
      render: (_: unknown, r: AdminGame) => r.phBonus > 0
        ? <span><span style={{ fontSize: 13, fontWeight: 600, color: '#1677ff' }}>{r.phBonus}</span><span style={{ fontSize: 10, color: '#999' }}> /30</span></span>
        : <span style={{ color: '#d9d9d9', fontSize: 11 }}>—</span>,
    },
    {
      title: '特性', key: 'features', width: 120,
      render: (_: unknown, r: AdminGame) => (r.hasFreespins || r.hasLobby || r.hasTables) ? (
        <Space wrap size={2}>
          {r.hasFreespins && <Tag color="purple" style={{ fontSize: 10, padding: '0 4px' }}>免费旋</Tag>}
          {r.hasLobby && <Tag color="cyan" style={{ fontSize: 10, padding: '0 4px' }}>大厅</Tag>}
          {r.hasTables && <Tag color="geekblue" style={{ fontSize: 10, padding: '0 4px' }}>桌台</Tag>}
        </Space>
      ) : <div style={{ color: '#ccc', fontSize: 11 }}>—</div>,
    },
    {
      title: '操作', key: 'actions', width: 65, fixed: 'right' as const,
      render: (_: unknown, r: AdminGame) => (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
          <Switch checked={r.isActive} size="small" loading={togglingUuid === r.uuid} onChange={(val) => onToggle(r, val)} />
          <Button type="link" size="small" style={{ padding: 0, height: 'auto', fontSize: 11 }} onClick={() => { setDetailGame(r); setDetailVisible(true) }}>详情</Button>
        </div>
      ),
    },
  ]

  const pagination: TablePaginationConfig = {
    current: page, pageSize: 20, total,
    showTotal: (t) => `共 ${t} 款`,
    showSizeChanger: false,
  }

  const filterSelect = (placeholder: string, value: string | undefined, onChange: (v: string | undefined) => void, options: { value: string; label: string }[]) => (
    <Select value={value} placeholder={placeholder} allowClear style={{ width: '100%' }} onChange={(v) => { onChange(v); void load(1) }} options={options} />
  )

  return (
    <div>
      <Space style={{ marginBottom: 12, width: '100%', justifyContent: 'space-between' }} align="center">
        <h2 style={{ margin: 0 }}>游戏管理</h2>
        <Space>
          <Button loading={translating} disabled={syncing} onClick={() => runBatchJob('translate', startTranslateGames)}>AI 翻译游戏名</Button>
          <Button type="primary" loading={syncing} disabled={translating} onClick={() => runBatchJob('sync', startSyncGames)}>同步游戏库</Button>
        </Space>
      </Space>

      <div style={{ background: '#fafafa', border: '1px solid #f0f0f0', borderRadius: 6, padding: '12px 16px', marginBottom: 14 }}>
        <Row gutter={[8, 8]}>
          <Col span={5}><Input.Search value={search} placeholder="搜索游戏名/关键词" onSearch={() => load(1)} allowClear onChange={(e) => setSearch(e.target.value)} /></Col>
          <Col span={4}>{filterSelect('游戏商', providerFilter, setProviderFilter, providers.map((p) => ({ value: p, label: p })))}</Col>
          <Col span={3}>{filterSelect('前端分类', sortCategoryFilter, setSortCategoryFilter, [{ value: 'slots', label: 'Slots' }, { value: 'fishing', label: 'Fishing' }, { value: 'live', label: 'Live' }, { value: 'bingo', label: 'Bingo' }, { value: 'crash', label: 'Crash' }, { value: 'table', label: 'Table' }])}</Col>
          <Col span={3}>{filterSelect('游戏主题', themeFilter, setThemeFilter, ['fishing', 'asian', 'mythology', 'fantasy', 'adventure', 'fruit', 'classic', 'animal'].map((v) => ({ value: v, label: v })))}</Col>
          <Col span={3}>{filterSelect('游戏风格', gameStyleFilter, setGameStyleFilter, ['asian', 'western', 'classic', 'modern'].map((v) => ({ value: v, label: v })))}</Col>
          <Col span={3}>{filterSelect('适合玩家', playerTypeFilter, setPlayerTypeFilter, [{ value: 'casual', label: 'casual 休闲' }, { value: 'regular', label: 'regular 普通' }, { value: 'high-roller', label: 'high-roller 高额' }])}</Col>
          <Col span={3}>{filterSelect('权重分段', weightRangeFilter, setWeightRangeFilter, [{ value: '80-100', label: '高热度 80-100' }, { value: '50-79', label: '中热度 50-79' }, { value: '1-49', label: '低热度 1-49' }, { value: '0-0', label: '未评分 0' }])}</Col>
          <Col span={3}>{filterSelect('波动性', volatilityFilter, setVolatilityFilter, [{ value: 'low', label: '低 Low' }, { value: 'medium', label: '中 Medium' }, { value: 'high', label: '高 High' }, { value: 'very-high', label: '极高 Very High' }])}</Col>
          <Col span={3}>{filterSelect('支持试玩', demoFilter, setDemoFilter, [{ value: 'true', label: '支持试玩' }, { value: 'false', label: '不支持' }])}</Col>
          <Col span={3}>{filterSelect('推荐首页', featuredFilter, setFeaturedFilter, [{ value: 'true', label: '已推荐' }, { value: 'false', label: '未推荐' }])}</Col>
          <Col span={3}>{filterSelect('技术', techFilter, setTechFilter, [{ value: 'HTML5', label: 'HTML5' }, { value: 'Flash', label: 'Flash' }])}</Col>
          <Col span={3}>{filterSelect('状态', activeFilter, setActiveFilter, [{ value: 'true', label: '已启用' }, { value: 'false', label: '已禁用' }])}</Col>
          <Col span={3} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Tag color="blue">共 {total} 款</Tag>
            <Button size="small" onClick={resetFilters}>重置</Button>
          </Col>
        </Row>
      </div>

      <Table
        columns={columns}
        dataSource={games}
        loading={loading}
        pagination={pagination}
        rowKey="uuid"
        size="small"
        scroll={{ x: 1400 }}
        onChange={handleTableChange}
      />

      {/* 详情弹窗 */}
      <Modal
        open={detailVisible}
        title={detailGame?.name}
        footer={null}
        onCancel={() => setDetailVisible(false)}
        width={680}
        styles={{ body: { maxHeight: '75vh', overflowY: 'auto', padding: '16px 20px' } }}
        destroyOnHidden
      >
        {detailGame && (
          <div>
            {(detailGame.imageHqUrl || detailGame.imageUrl) && (
              <div style={{ textAlign: 'center', marginBottom: 14 }}>
                <img src={detailGame.imageHqUrl || detailGame.imageUrl || ''} style={{ maxWidth: '100%', maxHeight: 160, objectFit: 'contain', borderRadius: 6 }} />
              </div>
            )}
            <Descriptions title="基本信息" column={2} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="UUID" span={2}><span style={{ fontSize: 11, fontFamily: 'monospace', wordBreak: 'break-all' }}>{detailGame.uuid}</span></Descriptions.Item>
              <Descriptions.Item label="游戏商">{detailGame.provider}{detailGame.providerId && <span style={{ color: '#999', fontSize: 11 }}> (ID: {detailGame.providerId})</span>}</Descriptions.Item>
              <Descriptions.Item label="子标签">{detailGame.label || '—'}</Descriptions.Item>
              <Descriptions.Item label="技术">{detailGame.technology ? <Tag color={detailGame.technology === 'HTML5' ? 'blue' : 'orange'}>{detailGame.technology}</Tag> : '—'}</Descriptions.Item>
              <Descriptions.Item label="状态"><Tag color={detailGame.isActive ? 'green' : 'red'}>{detailGame.isActive ? '已启用' : '已禁用'}</Tag></Descriptions.Item>
              <Descriptions.Item label="更新时间" span={2}>{detailGame.updatedAt ? new Date(detailGame.updatedAt).toLocaleString('zh-CN') : '—'}</Descriptions.Item>
            </Descriptions>
            <Descriptions title="分类信息" column={2} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="前端分类">{detailGame.sortCategory ? <Tag color={sortCategoryColor(detailGame.sortCategory)}>{detailGame.sortCategory}</Tag> : '—'}</Descriptions.Item>
              <Descriptions.Item label="游戏类型">{detailGame.type || '—'}</Descriptions.Item>
              <Descriptions.Item label="分类">{detailGame.category || '—'}</Descriptions.Item>
              <Descriptions.Item label="子分类">{detailGame.subCategory || '—'}</Descriptions.Item>
              <Descriptions.Item label="游戏主题">{detailGame.theme || '—'}</Descriptions.Item>
              <Descriptions.Item label="游戏风格">{detailGame.gameStyle || '—'}</Descriptions.Item>
              <Descriptions.Item label="适合玩家" span={2}>{detailGame.playerType ? <Tag color={playerTypeColor(detailGame.playerType)}>{detailGame.playerType}</Tag> : '—'}</Descriptions.Item>
            </Descriptions>
            <Descriptions title="游戏参数" column={2} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="RTP">{detailGame.rtp != null ? detailGame.rtp + '%' : '—'}</Descriptions.Item>
              <Descriptions.Item label="波动性">{detailGame.volatility ? <Tag color={volatilityColor(detailGame.volatility)}>{detailGame.volatility}</Tag> : '—'}</Descriptions.Item>
              <Descriptions.Item label="转轮数">{detailGame.reelsCount || '—'}</Descriptions.Item>
              <Descriptions.Item label="赔付线">{detailGame.linesCount ?? '—'}</Descriptions.Item>
            </Descriptions>
            <Descriptions title="多语言名称" column={1} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="英语 (en)">{detailGame.name}</Descriptions.Item>
              <Descriptions.Item label="印尼语 (id)">{detailGame.nameId || <span style={{ color: '#bbb' }}>未翻译</span>}</Descriptions.Item>
              <Descriptions.Item label="越南语 (vi)">{detailGame.nameVi || <span style={{ color: '#bbb' }}>未翻译</span>}</Descriptions.Item>
              <Descriptions.Item label="中文 (zh-CN)">{detailGame.nameZh || <span style={{ color: '#bbb' }}>未翻译</span>}</Descriptions.Item>
            </Descriptions>
            <Descriptions title="AI 富化数据" column={1} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="热度权重">
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <Progress type="line" percent={detailGame.weight} strokeWidth={8} strokeColor={weightColor(detailGame.weight)} showInfo={false} style={{ flex: 1, margin: 0 }} />
                  <span style={{ fontSize: 13, fontWeight: 500, width: 30 }}>{detailGame.weight}</span>
                </div>
              </Descriptions.Item>
              <Descriptions.Item label="PH热度(ph_bonus)"><span style={{ fontSize: 13, fontWeight: 500, color: '#1677ff' }}>{detailGame.phBonus}</span><span style={{ fontSize: 11, color: '#999' }}> / 30</span></Descriptions.Item>
              <Descriptions.Item label="推荐首页"><Tag color={detailGame.isFeatured ? 'gold' : 'default'}>{detailGame.isFeatured ? '已推荐' : '未推荐'}</Tag></Descriptions.Item>
              <Descriptions.Item label="中文简介"><span style={{ whiteSpace: 'pre-wrap' }}>{detailGame.descriptionZh || '—'}</span></Descriptions.Item>
              <Descriptions.Item label="英文简介"><span style={{ whiteSpace: 'pre-wrap', fontSize: 12 }}>{detailGame.descriptionEn || '—'}</span></Descriptions.Item>
              <Descriptions.Item label="搜索关键词"><span style={{ fontSize: 11, wordBreak: 'break-all' }}>{detailGame.searchKeywords || '—'}</span></Descriptions.Item>
              <Descriptions.Item label="权重更新时间">{detailGame.weightUpdatedAt ? new Date(detailGame.weightUpdatedAt).toLocaleString('zh-CN') : '—'}</Descriptions.Item>
            </Descriptions>
            <Descriptions title="功能特性" column={2} bordered size="small" style={{ marginBottom: 14 }}>
              <Descriptions.Item label="支持试玩"><Tag color={detailGame.hasDemo ? 'blue' : 'default'}>{detailGame.hasDemo ? '支持' : '不支持'}</Tag></Descriptions.Item>
              <Descriptions.Item label="手机端"><Tag color={detailGame.isMobile ? 'green' : 'default'}>{detailGame.isMobile ? '支持' : '不支持'}</Tag></Descriptions.Item>
              <Descriptions.Item label="免费旋转"><Tag color={detailGame.hasFreespins ? 'purple' : 'default'}>{detailGame.hasFreespins ? '支持' : '不支持'}</Tag></Descriptions.Item>
              <Descriptions.Item label="大厅模式"><Tag color={detailGame.hasLobby ? 'cyan' : 'default'}>{detailGame.hasLobby ? '支持' : '不支持'}</Tag></Descriptions.Item>
              <Descriptions.Item label="桌台" span={2}><Tag color={detailGame.hasTables ? 'geekblue' : 'default'}>{detailGame.hasTables ? '有' : '无'}</Tag></Descriptions.Item>
              {detailGame.tags?.length > 0 && <Descriptions.Item label="标签" span={2}>{detailGame.tags.map((t) => <Tag key={t} style={{ margin: 2 }}>{t}</Tag>)}</Descriptions.Item>}
            </Descriptions>
            <Descriptions title="图片" column={1} bordered size="small">
              <Descriptions.Item label="标准图">{detailGame.imageUrl ? <a href={detailGame.imageUrl} target="_blank" rel="noreferrer" style={{ fontSize: 11, wordBreak: 'break-all' }}>{detailGame.imageUrl}</a> : <span style={{ color: '#ccc' }}>—</span>}</Descriptions.Item>
              <Descriptions.Item label="高清图">{detailGame.imageHqUrl ? <a href={detailGame.imageHqUrl} target="_blank" rel="noreferrer" style={{ fontSize: 11, wordBreak: 'break-all' }}>{detailGame.imageHqUrl}</a> : <span style={{ color: '#ccc' }}>—</span>}</Descriptions.Item>
            </Descriptions>
          </div>
        )}
      </Modal>

      {/* 任务进度弹窗 */}
      <Modal
        open={jobModal.visible}
        title={jobModal.title}
        footer={null}
        closable={jobModal.closable}
        maskClosable={false}
        width={420}
        onCancel={() => setJobModal((m) => ({ ...m, visible: false }))}
      >
        <p style={{ marginBottom: 12, color: '#666' }}>{jobModal.msg}</p>
        {jobModal.total > 0
          ? <Progress percent={jobModal.percent} status={jobModal.status} />
          : <Spin />
        }
      </Modal>
    </div>
  )
}
