// apps/web-admin/src/views/TeamReferral.vue
<template>
  <div>
    <h2 style="margin-bottom:16px">三级分销管理</h2>

    <!-- 概览卡 -->
    <a-row :gutter="16" style="margin-bottom:20px">
      <a-col :span="6">
        <a-statistic title="活跃代理" :value="overview.activeAgents" />
      </a-col>
      <a-col :span="6">
        <a-statistic title="本月佣金总额" :value="phpDisplay(overview.thisMonthCommissionCents)" />
      </a-col>
      <a-col :span="6">
        <a-statistic title="待审提现笔数" :value="overview.pendingWithdrawalCount" />
      </a-col>
      <a-col :span="6">
        <a-statistic title="待审提现金额" :value="phpDisplay(overview.pendingWithdrawalCents)" />
      </a-col>
    </a-row>

    <!-- 费率配置 + 结算触发 -->
    <a-card title="佣金配置" style="margin-bottom:20px">
      <a-form layout="inline" :model="configForm" @finish="saveConfig">
        <a-form-item label="L1 比率(%)">
          <a-input-number v-model:value="configForm.l1_rate_pct" :min="0" :max="100" :step="0.5" style="width:90px" />
        </a-form-item>
        <a-form-item label="L2 比率(%)">
          <a-input-number v-model:value="configForm.l2_rate_pct" :min="0" :max="100" :step="0.5" style="width:90px" />
        </a-form-item>
        <a-form-item label="L3 比率(%)">
          <a-input-number v-model:value="configForm.l3_rate_pct" :min="0" :max="100" :step="0.5" style="width:90px" />
        </a-form-item>
        <a-form-item label="激活门槛(分)">
          <a-input-number v-model:value="configForm.min_activation_cents" :min="0" style="width:110px" />
        </a-form-item>
        <a-form-item label="最低提现(分)">
          <a-input-number v-model:value="configForm.min_withdrawal_cents" :min="0" style="width:110px" />
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" :loading="configSaving">保存配置</a-button>
        </a-form-item>
        <a-form-item>
          <a-popconfirm
            :title="`确认触发 ${settlePeriod} 月结算？`"
            @confirm="doSettle">
            <a-space>
              <a-input v-model:value="settlePeriod" style="width:110px" placeholder="YYYY-MM" />
              <a-button :loading="settling">触发结算</a-button>
            </a-space>
          </a-popconfirm>
        </a-form-item>
      </a-form>
    </a-card>

    <!-- Tab -->
    <a-tabs v-model:activeKey="activeTab">

      <!-- 代理列表 -->
      <a-tab-pane key="agents" tab="代理列表">
        <a-space style="margin-bottom:12px">
          <a-input v-model:value="agentSearch" placeholder="搜索用户ID/昵称" allow-clear style="width:200px" />
          <a-button type="primary" @click="loadAgents(1)">查询</a-button>
        </a-space>
        <a-table
          :columns="agentCols"
          :data-source="agents"
          :loading="agentsLoading"
          :pagination="agentPagination"
          row-key="userId"
          size="small"
          @change="(p: { current: number }) => loadAgents(p.current)"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'thisMonth'">
              {{ phpDisplay(record.thisMonthCommissionCents) }}
            </template>
            <template v-if="column.key === 'lifetime'">
              {{ phpDisplay(record.lifetimeEarnedCents) }}
            </template>
            <template v-if="column.key === 'team'">
              L1:{{ record.l1Count }} / L2:{{ record.l2Count }} / L3:{{ record.l3Count }}
            </template>
          </template>
        </a-table>
      </a-tab-pane>

      <!-- 佣金流水 -->
      <a-tab-pane key="commissions" tab="佣金流水">
        <a-space style="margin-bottom:12px">
          <a-input v-model:value="commFilter.period" placeholder="月份 YYYY-MM" allow-clear style="width:130px" />
          <a-input v-model:value="commFilter.beneficiaryId" placeholder="收益人ID" allow-clear style="width:150px" />
          <a-select v-model:value="commFilter.status" placeholder="状态" allow-clear style="width:110px">
            <a-select-option value="pending">pending</a-select-option>
            <a-select-option value="paid">paid</a-select-option>
            <a-select-option value="voided">voided</a-select-option>
          </a-select>
          <a-button type="primary" @click="loadCommissions(1)">查询</a-button>
        </a-space>
        <a-table
          :columns="commCols"
          :data-source="commissions"
          :loading="commissionsLoading"
          :pagination="commPagination"
          row-key="id"
          size="small"
          @change="(p: { current: number }) => loadCommissions(p.current)"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'ggr'">{{ phpDisplay(record.ggr_cents) }}</template>
            <template v-if="column.key === 'commission'">{{ phpDisplay(record.commission_cents) }}</template>
            <template v-if="column.key === 'status'">
              <a-tag :color="record.status === 'paid' ? 'green' : record.status === 'pending' ? 'orange' : 'default'">
                {{ record.status }}
              </a-tag>
            </template>
          </template>
        </a-table>
      </a-tab-pane>

      <!-- 提现审核 -->
      <a-tab-pane key="withdrawals" tab="提现审核">
        <a-space style="margin-bottom:12px">
          <a-select v-model:value="wdStatusFilter" placeholder="状态" allow-clear style="width:130px">
            <a-select-option value="pending">pending</a-select-option>
            <a-select-option value="approved">approved</a-select-option>
            <a-select-option value="rejected">rejected</a-select-option>
          </a-select>
          <a-button type="primary" @click="loadWithdrawals(1)">查询</a-button>
        </a-space>
        <a-table
          :columns="wdCols"
          :data-source="withdrawals"
          :loading="withdrawalsLoading"
          :pagination="wdPagination"
          row-key="id"
          size="small"
          @change="(p: { current: number }) => loadWithdrawals(p.current)"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'amount'">{{ phpDisplay(record.amount_cents) }}</template>
            <template v-if="column.key === 'status'">
              <a-tag :color="wdColor(record.status)">{{ record.status }}</a-tag>
            </template>
            <template v-if="column.key === 'actions'">
              <template v-if="record.status === 'pending'">
                <a-popconfirm title="确认批准此提现？" @confirm="doApprove(record.id)">
                  <a-button type="link" size="small" style="color:#52c41a">批准</a-button>
                </a-popconfirm>
                <a-button type="link" size="small" danger @click="openReject(record)">驳回</a-button>
              </template>
              <span v-else>-</span>
            </template>
          </template>
        </a-table>
      </a-tab-pane>
    </a-tabs>

    <!-- 驳回 modal -->
    <a-modal v-model:open="rejectModal.visible" title="驳回原因" @ok="doReject" :confirm-loading="opLoading">
      <a-input v-model:value="rejectModal.reason" placeholder="请输入驳回原因" />
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import {
  getTeamOverview, getTeamAgents, getTeamCommissions, getTeamWithdrawals,
  getTeamConfig, updateTeamConfig, triggerTeamSettle,
  approveTeamWithdrawal, rejectTeamWithdrawal,
  type TeamOverview, type TeamAgent, type TeamCommission, type TeamWithdrawalAdmin, type TeamConfig,
} from '../api.js'

// ── 概览 ─────────────────────────────────────────────────────────────────────
const overview = reactive<TeamOverview>({ activeAgents: 0, thisMonthCommissionCents: 0, pendingWithdrawalCount: 0, pendingWithdrawalCents: 0 })

// ── 配置 ─────────────────────────────────────────────────────────────────────
const configForm  = reactive<Partial<TeamConfig>>({})
const configSaving = ref(false)
const settling    = ref(false)
const settlePeriod = ref(currentPeriod())

async function loadConfig() {
  const cfg = await getTeamConfig()
  Object.assign(configForm, cfg)
}

async function saveConfig() {
  configSaving.value = true
  try {
    await updateTeamConfig(configForm)
    message.success('配置已保存')
  } catch (e) {
    message.error('保存失败')
  } finally {
    configSaving.value = false
  }
}

async function doSettle() {
  settling.value = true
  try {
    await triggerTeamSettle(settlePeriod.value)
    message.success(`${settlePeriod.value} 结算已触发，后台处理中`)
  } catch (e) {
    message.error(e instanceof Error ? e.message : '触发失败')
  } finally {
    settling.value = false
  }
}

// ── 代理列表 ─────────────────────────────────────────────────────────────────
const activeTab    = ref('agents')
const agentSearch  = ref('')
const agents       = ref<TeamAgent[]>([])
const agentsTotal  = ref(0)
const agentsPage   = ref(1)
const agentsLoading = ref(false)

const agentPagination = computed(() => ({
  current: agentsPage.value, pageSize: 20, total: agentsTotal.value,
  showTotal: (t: number) => `共 ${t} 条`,
}))

const agentCols = [
  { title: '用户ID',    dataIndex: 'userId',      key: 'userId',   width: 110 },
  { title: '昵称',      dataIndex: 'displayName',  key: 'name' },
  { title: '团队规模',  key: 'team',               width: 160 },
  { title: '本月佣金',  key: 'thisMonth',           width: 120 },
  { title: '累计收益',  key: 'lifetime',            width: 120 },
  { title: '开启时间',  dataIndex: 'optedInAt',     key: 'optedInAt', width: 160 },
]

async function loadAgents(page = 1) {
  agentsLoading.value = true
  try {
    const data = await getTeamAgents({ search: agentSearch.value, page, pageSize: 20 })
    agents.value = data.items
    agentsTotal.value = data.total
    agentsPage.value = page
  } finally {
    agentsLoading.value = false
  }
}

// ── 佣金流水 ─────────────────────────────────────────────────────────────────
const commFilter = reactive({ period: '', beneficiaryId: '', status: undefined as string | undefined })
const commissions     = ref<TeamCommission[]>([])
const commissionsTotal = ref(0)
const commissionsPage  = ref(1)
const commissionsLoading = ref(false)

const commPagination = computed(() => ({
  current: commissionsPage.value, pageSize: 50, total: commissionsTotal.value,
  showTotal: (t: number) => `共 ${t} 条`,
}))

const commCols = [
  { title: '月份',       dataIndex: 'period',           key: 'period',     width: 90 },
  { title: '收益人',     dataIndex: 'beneficiary_name', key: 'beneficiary' },
  { title: '下线',       dataIndex: 'from_name',        key: 'from' },
  { title: '层级',       dataIndex: 'level',            key: 'level',      width: 60 },
  { title: 'GGR',       key: 'ggr',                    width: 110 },
  { title: '费率',       dataIndex: 'rate_pct',         key: 'rate',       width: 70 },
  { title: '佣金',       key: 'commission',             width: 110 },
  { title: '状态',       key: 'status',                 width: 90 },
]

async function loadCommissions(page = 1) {
  commissionsLoading.value = true
  try {
    const data = await getTeamCommissions({ ...commFilter, page })
    commissions.value = data.items
    commissionsTotal.value = data.total
    commissionsPage.value = page
  } finally {
    commissionsLoading.value = false
  }
}

// ── 提现审核 ─────────────────────────────────────────────────────────────────
const wdStatusFilter  = ref<string | undefined>()
const withdrawals     = ref<TeamWithdrawalAdmin[]>([])
const withdrawalsTotal = ref(0)
const withdrawalsPage  = ref(1)
const withdrawalsLoading = ref(false)
const opLoading = ref(false)
const rejectModal = reactive({ visible: false, id: 0, reason: '' })

const wdPagination = computed(() => ({
  current: withdrawalsPage.value, pageSize: 20, total: withdrawalsTotal.value,
  showTotal: (t: number) => `共 ${t} 条`,
}))

const wdCols = [
  { title: 'ID',     dataIndex: 'id',           key: 'id',      width: 80 },
  { title: '用户',   dataIndex: 'display_name', key: 'user' },
  { title: '用户ID', dataIndex: 'user_id',      key: 'userId',  width: 110 },
  { title: '金额',   key: 'amount',             width: 110 },
  { title: '状态',   key: 'status',             width: 90 },
  { title: '申请时间', dataIndex: 'created_at',  key: 'createdAt', width: 160 },
  { title: '操作',   key: 'actions',            width: 120 },
]

function wdColor(s: string) {
  return s === 'approved' ? 'green' : s === 'pending' ? 'orange' : s === 'rejected' ? 'red' : 'default'
}

async function loadWithdrawals(page = 1) {
  withdrawalsLoading.value = true
  try {
    const data = await getTeamWithdrawals({ status: wdStatusFilter.value, page })
    withdrawals.value = data.items
    withdrawalsTotal.value = data.total
    withdrawalsPage.value = page
  } finally {
    withdrawalsLoading.value = false
  }
}

async function doApprove(id: number) {
  opLoading.value = true
  try {
    await approveTeamWithdrawal(id)
    message.success('已批准')
    await Promise.all([loadWithdrawals(withdrawalsPage.value), loadOverview()])
  } catch (e) {
    message.error(e instanceof Error ? e.message : '操作失败')
  } finally {
    opLoading.value = false
  }
}

function openReject(record: TeamWithdrawalAdmin) {
  rejectModal.id = record.id
  rejectModal.reason = ''
  rejectModal.visible = true
}

async function doReject() {
  opLoading.value = true
  try {
    await rejectTeamWithdrawal(rejectModal.id, rejectModal.reason)
    rejectModal.visible = false
    message.success('已驳回')
    await loadWithdrawals(withdrawalsPage.value)
  } catch (e) {
    message.error(e instanceof Error ? e.message : '操作失败')
  } finally {
    opLoading.value = false
  }
}

// ── 工具 ─────────────────────────────────────────────────────────────────────
function phpDisplay(cents: number) {
  return '₱' + ((cents ?? 0) / 100).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function currentPeriod() {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

async function loadOverview() {
  const data = await getTeamOverview()
  Object.assign(overview, data)
}

onMounted(() => {
  void loadOverview()
  void loadConfig()
  void loadAgents(1)
  void loadWithdrawals(1)
})
</script>

// apps/web-admin/src/views/TeamReferral.tsx
import { useEffect, useState } from 'react'
import { Row, Col, Statistic, Card, Form, InputNumber, Button, Input, Select, Popconfirm, Table, Tabs, Tag, Modal, message, Drawer, Tree, Spin, Space } from 'antd'
import type { TablePaginationConfig } from 'antd'
import {
  getTeamOverview, getTeamAgents, getTeamCommissions, getTeamWithdrawals,
  getTeamConfig, updateTeamConfig, triggerTeamSettle,
  approveTeamWithdrawal, rejectTeamWithdrawal, getTeamAgentTree,
  type TeamOverview, type TeamAgent, type TeamCommission, type TeamWithdrawalAdmin, type TeamConfig, type TeamTreeMember,
} from '../api'

interface TreeNodeItem { key: string; title: React.ReactNode; children?: TreeNodeItem[] }

function buildTreeNode(m: TeamTreeMember, level: 1 | 2 | 3): TreeNodeItem {
  const levelColor = level === 1 ? 'gold' : level === 2 ? 'blue' : 'green'
  return {
    key: `l${level}-${m.userId}`,
    title: (
      <span style={{ display: 'inline-flex', gap: 5, alignItems: 'center', flexWrap: 'wrap' }}>
        <Tag color={levelColor} style={{ fontSize: 10, padding: '0 4px', margin: 0, lineHeight: '16px' }}>L{level}</Tag>
        <span style={{ fontWeight: 500 }}>{m.displayName}</span>
        <span style={{ color: '#bbb', fontSize: 11 }}>{m.userId}</span>
        {m.isAgent && <Tag color="purple" style={{ fontSize: 10, padding: '0 4px', margin: 0, lineHeight: '16px' }}>代理</Tag>}
        {m.thisMonthCents > 0 && <span style={{ color: '#1677ff', fontSize: 11 }}>₱{(m.thisMonthCents / 100).toFixed(2)}</span>}
      </span>
    ),
    children: m.children.length > 0 ? m.children.map((c) => buildTreeNode(c, (level + 1) as 2 | 3)) : undefined,
  }
}

function phpDisplay(cents: number) {
  return '₱' + ((cents ?? 0) / 100).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function currentPeriod() {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

function wdColor(s: string) {
  return s === 'approved' ? 'green' : s === 'pending' ? 'orange' : s === 'rejected' ? 'red' : 'default'
}

export default function TeamReferral() {
  const [overview, setOverview] = useState<TeamOverview>({ activeAgents: 0, thisMonthCommissionCents: 0, pendingWithdrawalCount: 0, pendingWithdrawalCents: 0 })
  const [configForm] = Form.useForm<TeamConfig>()
  const [configSaving, setConfigSaving] = useState(false)
  const [settling, setSettling] = useState(false)
  const [settlePeriod, setSettlePeriod] = useState(currentPeriod())
  const [activeTab, setActiveTab] = useState('agents')

  const [agentSearch, setAgentSearch] = useState('')
  const [agents, setAgents] = useState<TeamAgent[]>([])
  const [agentsTotal, setAgentsTotal] = useState(0)
  const [agentsPage, setAgentsPage] = useState(1)
  const [agentsLoading, setAgentsLoading] = useState(false)

  const [commFilter, setCommFilter] = useState({ period: '', beneficiaryId: '', status: undefined as string | undefined })
  const [commissions, setCommissions] = useState<TeamCommission[]>([])
  const [commissionsTotal, setCommissionsTotal] = useState(0)
  const [commissionsPage, setCommissionsPage] = useState(1)
  const [commissionsLoading, setCommissionsLoading] = useState(false)

  const [wdStatusFilter, setWdStatusFilter] = useState<string | undefined>()
  const [withdrawals, setWithdrawals] = useState<TeamWithdrawalAdmin[]>([])
  const [withdrawalsTotal, setWithdrawalsTotal] = useState(0)
  const [withdrawalsPage, setWithdrawalsPage] = useState(1)
  const [withdrawalsLoading, setWithdrawalsLoading] = useState(false)
  const [opLoading, setOpLoading] = useState(false)
  const [rejectModal, setRejectModal] = useState({ visible: false, id: 0, reason: '' })

  const [treeVisible, setTreeVisible] = useState(false)
  const [treeAgent, setTreeAgent] = useState<TeamAgent | null>(null)
  const [treeData, setTreeData] = useState<{ l1Members: TeamTreeMember[] } | null>(null)
  const [treeLoading, setTreeLoading] = useState(false)
  const [treeExpandedKeys, setTreeExpandedKeys] = useState<(string | number)[]>([])

  async function loadOverview() {
    const data = await getTeamOverview()
    setOverview(data)
  }

  async function loadConfig() {
    const cfg = await getTeamConfig()
    configForm.setFieldsValue(cfg)
  }

  async function saveConfig() {
    const values = configForm.getFieldsValue()
    setConfigSaving(true)
    try {
      await updateTeamConfig(values)
      message.success('配置已保存')
    } catch { message.error('保存失败') }
    finally { setConfigSaving(false) }
  }

  async function doSettle() {
    setSettling(true)
    try {
      await triggerTeamSettle(settlePeriod)
      message.success(`${settlePeriod} 结算已触发，后台处理中`)
    } catch (e) { message.error(e instanceof Error ? e.message : '触发失败') }
    finally { setSettling(false) }
  }

  async function openTree(agent: TeamAgent) {
    setTreeAgent(agent)
    setTreeData(null)
    setTreeVisible(true)
    setTreeLoading(true)
    try {
      const data = await getTeamAgentTree(agent.userId)
      setTreeData(data)
      setTreeExpandedKeys([
        `root-${agent.userId}`,
        ...data.l1Members.map((m) => `l1-${m.userId}`),
      ])
    } catch { message.error('加载团队树失败') }
    finally { setTreeLoading(false) }
  }

  function expandAll() {
    if (!treeAgent || !treeData) return
    const keys: (string | number)[] = [`root-${treeAgent.userId}`]
    for (const l1 of treeData.l1Members) {
      keys.push(`l1-${l1.userId}`)
      for (const l2 of l1.children) keys.push(`l2-${l2.userId}`)
    }
    setTreeExpandedKeys(keys)
  }

  async function loadAgents(page = 1) {
    setAgentsLoading(true)
    try {
      const data = await getTeamAgents({ search: agentSearch, page, pageSize: 20 })
      setAgents(data.items); setAgentsTotal(data.total); setAgentsPage(page)
    } finally { setAgentsLoading(false) }
  }

  async function loadCommissions(page = 1) {
    setCommissionsLoading(true)
    try {
      const data = await getTeamCommissions({ ...commFilter, page })
      setCommissions(data.items); setCommissionsTotal(data.total); setCommissionsPage(page)
    } finally { setCommissionsLoading(false) }
  }

  async function loadWithdrawals(page = 1) {
    setWithdrawalsLoading(true)
    try {
      const data = await getTeamWithdrawals({ status: wdStatusFilter, page })
      setWithdrawals(data.items); setWithdrawalsTotal(data.total); setWithdrawalsPage(page)
    } finally { setWithdrawalsLoading(false) }
  }

  async function doApprove(id: number) {
    setOpLoading(true)
    try {
      await approveTeamWithdrawal(id)
      message.success('已批准')
      await Promise.all([loadWithdrawals(withdrawalsPage), loadOverview()])
    } catch (e) { message.error(e instanceof Error ? e.message : '操作失败') }
    finally { setOpLoading(false) }
  }

  async function doReject() {
    setOpLoading(true)
    try {
      await rejectTeamWithdrawal(rejectModal.id, rejectModal.reason)
      setRejectModal((m) => ({ ...m, visible: false }))
      message.success('已驳回')
      await loadWithdrawals(withdrawalsPage)
    } catch (e) { message.error(e instanceof Error ? e.message : '操作失败') }
    finally { setOpLoading(false) }
  }

  useEffect(() => {
    void loadOverview(); void loadConfig(); void loadAgents(1); void loadWithdrawals(1)
  }, [])

  const agentCols = [
    { title: '用户ID', dataIndex: 'userId', key: 'userId', width: 110 },
    { title: '昵称', dataIndex: 'displayName', key: 'name' },
    {
      title: '团队规模', key: 'team', width: 200,
      render: (_: unknown, r: TeamAgent) => (
        <Space size={4}>
          <Tag color="gold" style={{ margin: 0 }}>L1 · {r.l1Count}</Tag>
          <Tag color="blue" style={{ margin: 0 }}>L2 · {r.l2Count}</Tag>
          <Tag color="green" style={{ margin: 0 }}>L3 · {r.l3Count}</Tag>
        </Space>
      ),
    },
    { title: '本月佣金', key: 'thisMonth', width: 120, render: (_: unknown, r: TeamAgent) => phpDisplay(r.thisMonthCommissionCents) },
    { title: '累计收益', key: 'lifetime', width: 120, render: (_: unknown, r: TeamAgent) => phpDisplay(r.lifetimeEarnedCents) },
    { title: '开启时间', dataIndex: 'optedInAt', key: 'optedInAt', width: 160 },
    {
      title: '操作', key: 'actions', width: 90,
      render: (_: unknown, r: TeamAgent) => (
        <Button type="link" size="small" onClick={() => openTree(r)}>团队树</Button>
      ),
    },
  ]

  const commCols = [
    { title: '月份', dataIndex: 'period', key: 'period', width: 90 },
    { title: '收益人', dataIndex: 'beneficiary_name', key: 'beneficiary' },
    { title: '下线', dataIndex: 'from_name', key: 'from' },
    { title: '层级', dataIndex: 'level', key: 'level', width: 60 },
    { title: 'GGR', key: 'ggr', width: 110, render: (_: unknown, r: TeamCommission) => phpDisplay(r.ggr_cents) },
    { title: '费率', dataIndex: 'rate_pct', key: 'rate', width: 70 },
    { title: '佣金', key: 'commission', width: 110, render: (_: unknown, r: TeamCommission) => phpDisplay(r.commission_cents) },
    { title: '状态', key: 'status', width: 90, render: (_: unknown, r: TeamCommission) => <Tag color={r.status === 'paid' ? 'green' : r.status === 'pending' ? 'orange' : 'default'}>{r.status}</Tag> },
  ]

  const wdCols = [
    { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
    { title: '用户', dataIndex: 'display_name', key: 'user' },
    { title: '用户ID', dataIndex: 'user_id', key: 'userId', width: 110 },
    { title: '金额', key: 'amount', width: 110, render: (_: unknown, r: TeamWithdrawalAdmin) => phpDisplay(r.amount_cents) },
    { title: '状态', key: 'status', width: 90, render: (_: unknown, r: TeamWithdrawalAdmin) => <Tag color={wdColor(r.status)}>{r.status}</Tag> },
    { title: '申请时间', dataIndex: 'created_at', key: 'createdAt', width: 160 },
    {
      title: '操作', key: 'actions', width: 120,
      render: (_: unknown, r: TeamWithdrawalAdmin) => r.status === 'pending' ? (
        <>
          <Popconfirm title="确认批准此提现？" onConfirm={() => doApprove(r.id)}>
            <Button type="link" size="small" style={{ color: '#52c41a' }}>批准</Button>
          </Popconfirm>
          <Button type="link" size="small" danger onClick={() => setRejectModal({ visible: true, id: r.id, reason: '' })}>驳回</Button>
        </>
      ) : <span>-</span>,
    },
  ]

  const agentPagination: TablePaginationConfig = { current: agentsPage, pageSize: 20, total: agentsTotal, showTotal: (t) => `共 ${t} 条`, onChange: (p) => loadAgents(p) }
  const commPagination: TablePaginationConfig = { current: commissionsPage, pageSize: 50, total: commissionsTotal, showTotal: (t) => `共 ${t} 条`, onChange: (p) => loadCommissions(p) }
  const wdPagination: TablePaginationConfig = { current: withdrawalsPage, pageSize: 20, total: withdrawalsTotal, showTotal: (t) => `共 ${t} 条`, onChange: (p) => loadWithdrawals(p) }

  return (
    <div>
      <h2 style={{ marginBottom: 16 }}>三级分销管理</h2>

      <Row gutter={16} style={{ marginBottom: 20 }}>
        <Col span={6}><Statistic title="活跃代理" value={overview.activeAgents} /></Col>
        <Col span={6}><Statistic title="本月佣金总额" value={phpDisplay(overview.thisMonthCommissionCents)} /></Col>
        <Col span={6}><Statistic title="待审提现笔数" value={overview.pendingWithdrawalCount} /></Col>
        <Col span={6}><Statistic title="待审提现金额" value={phpDisplay(overview.pendingWithdrawalCents)} /></Col>
      </Row>

      <Card title="佣金配置" style={{ marginBottom: 20 }}>
        <Form form={configForm} layout="inline" onFinish={saveConfig}>
          <Form.Item label="L1 比率(%)" name="l1_rate_pct"><InputNumber min={0} max={100} step={0.5} style={{ width: 90 }} /></Form.Item>
          <Form.Item label="L2 比率(%)" name="l2_rate_pct"><InputNumber min={0} max={100} step={0.5} style={{ width: 90 }} /></Form.Item>
          <Form.Item label="L3 比率(%)" name="l3_rate_pct"><InputNumber min={0} max={100} step={0.5} style={{ width: 90 }} /></Form.Item>
          <Form.Item label="激活门槛(分)" name="min_activation_cents"><InputNumber min={0} style={{ width: 110 }} /></Form.Item>
          <Form.Item label="最低提现(分)" name="min_withdrawal_cents"><InputNumber min={0} style={{ width: 110 }} /></Form.Item>
          <Form.Item><Button type="primary" htmlType="submit" loading={configSaving}>保存配置</Button></Form.Item>
          <Form.Item>
            <Popconfirm title={`确认触发 ${settlePeriod} 月结算？`} onConfirm={doSettle}>
              <Input.Group compact>
                <Input value={settlePeriod} onChange={(e) => setSettlePeriod(e.target.value)} style={{ width: 110 }} placeholder="YYYY-MM" />
                <Button loading={settling}>触发结算</Button>
              </Input.Group>
            </Popconfirm>
          </Form.Item>
        </Form>
      </Card>

      <Tabs activeKey={activeTab} onChange={setActiveTab} items={[
        {
          key: 'agents', label: '代理列表',
          children: (
            <div>
              <div style={{ marginBottom: 12, display: 'flex', gap: 8 }}>
                <Input value={agentSearch} onChange={(e) => setAgentSearch(e.target.value)} placeholder="搜索用户ID/昵称" allowClear style={{ width: 200 }} />
                <Button type="primary" onClick={() => loadAgents(1)}>查询</Button>
              </div>
              <Table columns={agentCols} dataSource={agents} loading={agentsLoading} pagination={agentPagination} rowKey="userId" size="small" />
            </div>
          ),
        },
        {
          key: 'commissions', label: '佣金流水',
          children: (
            <div>
              <div style={{ marginBottom: 12, display: 'flex', gap: 8 }}>
                <Input value={commFilter.period} onChange={(e) => setCommFilter((f) => ({ ...f, period: e.target.value }))} placeholder="月份 YYYY-MM" allowClear style={{ width: 130 }} />
                <Input value={commFilter.beneficiaryId} onChange={(e) => setCommFilter((f) => ({ ...f, beneficiaryId: e.target.value }))} placeholder="收益人ID" allowClear style={{ width: 150 }} />
                <Select value={commFilter.status} placeholder="状态" allowClear style={{ width: 110 }} onChange={(v) => setCommFilter((f) => ({ ...f, status: v }))} options={[{ value: 'pending', label: 'pending' }, { value: 'paid', label: 'paid' }, { value: 'voided', label: 'voided' }]} />
                <Button type="primary" onClick={() => loadCommissions(1)}>查询</Button>
              </div>
              <Table columns={commCols} dataSource={commissions} loading={commissionsLoading} pagination={commPagination} rowKey="id" size="small" />
            </div>
          ),
        },
        {
          key: 'withdrawals', label: '提现审核',
          children: (
            <div>
              <div style={{ marginBottom: 12, display: 'flex', gap: 8 }}>
                <Select value={wdStatusFilter} placeholder="状态" allowClear style={{ width: 130 }} onChange={setWdStatusFilter} options={[{ value: 'pending', label: 'pending' }, { value: 'approved', label: 'approved' }, { value: 'rejected', label: 'rejected' }]} />
                <Button type="primary" onClick={() => loadWithdrawals(1)}>查询</Button>
              </div>
              <Table columns={wdCols} dataSource={withdrawals} loading={withdrawalsLoading} pagination={wdPagination} rowKey="id" size="small" />
            </div>
          ),
        },
      ]} />

      <Modal open={rejectModal.visible} title="驳回原因" onOk={doReject} confirmLoading={opLoading} onCancel={() => setRejectModal((m) => ({ ...m, visible: false }))}>
        <Input value={rejectModal.reason} onChange={(e) => setRejectModal((m) => ({ ...m, reason: e.target.value }))} placeholder="请输入驳回原因" />
      </Modal>

      <Drawer
        title={
          treeAgent ? (
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingRight: 32 }}>
              <span>
                <Tag color="gold">代理</Tag>
                <span style={{ fontWeight: 600 }}>{treeAgent.displayName}</span>
                <span style={{ color: '#999', fontSize: 12, marginLeft: 6 }}>{treeAgent.userId}</span>
              </span>
              <Space size={6}>
                <Button size="small" onClick={expandAll} disabled={treeLoading}>展开全部</Button>
                <Button size="small" onClick={() => treeAgent && setTreeExpandedKeys([`root-${treeAgent.userId}`])} disabled={treeLoading}>折叠</Button>
              </Space>
            </div>
          ) : '团队树'
        }
        open={treeVisible}
        onClose={() => setTreeVisible(false)}
        width={560}
        destroyOnHidden
        styles={{ body: { padding: '12px 16px', overflow: 'auto' } }}
      >
        {treeLoading && <div style={{ textAlign: 'center', padding: 40 }}><Spin /></div>}
        {!treeLoading && treeAgent && treeData && (
          treeData.l1Members.length === 0
            ? <div style={{ color: '#999', textAlign: 'center', padding: 40 }}>该代理暂无下线</div>
            : <Tree
                showLine={{ showLeafIcon: false }}
                expandedKeys={treeExpandedKeys}
                onExpand={(keys) => setTreeExpandedKeys(keys as (string | number)[])}
                blockNode
                treeData={[{
                  key: `root-${treeAgent.userId}`,
                  title: (
                    <span style={{ display: 'inline-flex', gap: 5, alignItems: 'center' }}>
                      <Tag color="gold" style={{ fontSize: 10, padding: '0 4px', margin: 0, lineHeight: '16px' }}>代理</Tag>
                      <span style={{ fontWeight: 600 }}>{treeAgent.displayName}</span>
                      <span style={{ color: '#999', fontSize: 11 }}>{treeAgent.userId}</span>
                      <span style={{ color: '#aaa', fontSize: 11 }}>
                        L1·{treeAgent.l1Count} L2·{treeAgent.l2Count} L3·{treeAgent.l3Count}
                      </span>
                    </span>
                  ),
                  children: treeData.l1Members.map((m) => buildTreeNode(m, 1)),
                }] as TreeNodeItem[]}
              />
        )}
      </Drawer>
    </div>
  )
}
